### ISSUE TITLE
Spark fails with latest Docker image

### ISSUE THREAD

**Issue by candily** [polynote/polynote#1001]
**Description**
`spark-submit` fails when executing first cell of "Polynote 0.3.12: examples/Scala Spark to Pandas.ipynb" with `polynote/polynote:latest` Docker image.

**Reproduction**
1. Run ```docker run --rm -it -p 127.0.0.1:8192:8192 -p 127.0.0.1:4040-4050:4040-4050 -v `pwd`/config.yml:/opt/config/config.yml -v `pwd`/notebooks:/opt/notebooks/ polynote/polynote:latest --config /opt/config/config.yml```.
2. Open the "Scala Spark to Pandas.ipynb" example.
3. Execute the first cell.

**Environment**

```
docker run --rm -it -p 127.0.0.1:8192:8192 -p 127.0.0.1:4040-4050:4040-4050 -v `pwd`/config.yml:/opt/config/config.yml -v `pwd`/notebooks:/opt/notebooks/ polynote/polynote:latest --config /opt/config/config.yml
```

**Configuration**

```
listen:
  host: 0.0.0.0

storage:
  dir: /opt/notebooks
  mounts:
    examples:
      dir: examples
```

**Notebook**
https://github.com/polynote/polynote/blob/master/docs/examples/Scala%20Spark%20to%20Pandas.ipynb

**Logs**

```
[ERROR]   (Logged from NotebookSession.scala:174)
   |     java.io.IOException: Cannot run program "spark-submit": error=2, No such file or directory
   |     java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
   |     polynote.kernel.remote.SocketTransport$DeploySubprocess$$anonfun$deployKernel$1$$anonfun$apply$65$$anonfun$apply$66$$anonfun$apply$67$$anonfun$apply$68$$anonfun$apply$69.apply(transport.scala:347)
   |     polynote.kernel.remote.SocketTransport$DeploySubprocess$$anonfun$deployKernel$1$$anonfun$apply$65$$anonfun$apply$66$$anonfun$apply$67$$anonfun$apply$68$$anonfun$apply$69.apply(transport.scala:347)
   |     zio.internal.FiberContext.evaluateNow(FiberContext.scala:458)
   |     zio.internal.FiberContext.zio$internal$FiberContext$$run$body$2(FiberContext.scala:687)
   |     zio.internal.FiberContext$$anonfun$12.run(FiberContext.scala:687)
   |     java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   |     java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   |     java.lang.Thread.run(Thread.java:748)
```

**Comment by valenterry** [comment]
This seems to be fixed with the latest version. @candily I think you can close the issue.

**Comment by jonathanindig** [comment]
Thanks @valenterry for the update. I'll go ahead an close the issue. @candily feel free to reopen if you still see a problem with the latest release (version `0.4.0`)
