### ISSUE TITLE
Some member in Scala package cant be resolved

### ISSUE THREAD

**Issue by counter2015** [polynote/polynote#1008]
**Description**
I'm trying [cats](https://www.scalawithcats.com/dist/scala-with-cats.html) with polynote, the member in cats package 
cant be resolved.
```scala
import cats.instances.int._    // for Show
import cats.instances.string._ // for Show

val showInt:    Show[Int]    = Show.apply[Int]
val showString: Show[String] = Show.apply[String]
```
**Reproduction**
1. add Dependencies in `Configuration & dependencies` : scala/jvm org.typelevel:cats-core_2.13:2.1.0
2. type code following
```scala
import cats.Show // it works
import cats.instances.int // rasise error: Error object int is not a member of package cats.instances (Line 2)
```
However, when I try to run it in sbt console, it works
```scala
Welcome to Scala 2.13.1 (OpenJDK 64-Bit Server VM, Java 11.0.9.1).
Type in expressions for evaluation. Or try :help.

scala> import cats.instances.int
import cats.instances.int

scala> int
res0: cats.instances.int.type = cats.instances.package$int$@58dead3e
```

**Environment**

Polynote Version:  0.3.12
build commit: 72a6f4426064ad9875db93a
sbt version: 1.3.13

- Polynote Version: 
   - 0.3.12
- Operating System: 
  - Mac OS BIg Surge 11.1
- JVM Version:
  - OpenJDK 64-Bit Server VM, Java 11.0.9.1
- Python Version:
  - 3.8.5 [Clang 11.0.3 (clang-1103.0.32.62)] on darwin

- The command you are using to start Polynote:
  - `python ./polynote.py`

**Configuration**

defualt config

![image](https://user-images.githubusercontent.com/13608862/103133451-7fc4ef80-46e5-11eb-9233-17d9d3efffd6.png)
![image](https://user-images.githubusercontent.com/13608862/103133461-8c494800-46e5-11eb-9055-ccd4c7ebe15d.png)

**Comment by jonathanindig** [comment]
I think this is likely due to the scala version in the dependency - `org.typelevel:cats-core_2.13:2.1.0`. Unfortunately Polynote is only distributed with 2.11 or 2.12 right now (unless you have recompiled it to 2.13 yourself).
