### ISSUE TITLE
Scroll to running cells 

### ISSUE THREAD

**Issue by jonathanindig** [polynote/polynote#1021]
It would be cool if the UI would automatically "follow" (i.e. scroll) executing cells (if nothing else is currently selected).

**Comment by jeremyrsmith** [comment]
I could see this getting kind of annoying though – e.g. you're trying to read ahead in the notebook while a Spark task runs for 10 minutes in cell 1, and then all of a sudden it scrolls up to cell 2 because the spark task finished. It would have to be a configurable preference.

**Comment by jonathanindig** [comment]
Agreed, could be a bit tricky to figure out user intent here.

**Comment by omidmogasemi** [comment]
For anyone looking for updates on this, see #1274

**Comment by omidmogasemi** [comment]
For anyone looking for updates on this, see #1274
