### ISSUE TITLE
Maven releases not up to date.

### ISSUE THREAD

**Issue by drewrobb** [polynote/polynote#1022]
For releases published at https://mvnrepository.com/artifact/org.polynote/polynote-runtime, the latest published version is 0.3.8, where as the latest project release here is 0.3.12. Is there a place where up to date maven releases will continue to be published?

Thanks!

**Comment by jonathanindig** [comment]
Thanks for the note @drewrobb. @jeremyrsmith, can you look into this when you get the chance? Thanks!

**Comment by dnzprmksz** [comment]
Also latest release on github is on Sep 17, 2020 · 324 commits to master since this release. Is there any reason for you to stop releases? We are still using 0.3.12, but seems like there are a lot of commits since then. @jonathanindig

**Comment by jeremyrsmith** [comment]
We've released 0.4.0, to GitHub as well as Maven Central.

We were working on it all this time, it just took us a while to get some of the kinks worked out.

**Comment by dnzprmksz** [comment]
Great work @jeremyrsmith thanks for it! Appreciate your work 💪 

I was just curious about the releases since it has been a long time. Polynote is my favorite and go-to notebook since Nov 2019, wow time flies.
