### ISSUE TITLE
View cells side-by-side

### ISSUE THREAD

**Issue by jonathanindig** [polynote/polynote#1023]
Support for rendering cells side-by-side / horizontally. Useful for comparisons, plots, etc.

**Comment by omidmogasemi** [comment]
@jonathanindig Would this be rendering some output side-by-side to a cell, or actually [placing two code cells and their respective output next to each other horizontally](https://i.stack.imgur.com/HDhoR.png)? I think the latter makes more sense in this context - not sure if this data should be stored on the browser or as cell metadata, however.
