### ISSUE TITLE
Matplotlib output configurability

### ISSUE THREAD

**Issue by jonathanindig** [polynote/polynote#1037]
Currently, Polynote's matplotlib integration is set to saving and displaying plots as SVGs: https://github.com/polynote/polynote/blob/master/polynote-kernel/src/main/scala/polynote/kernel/interpreter/python/PythonInterpreter.scala#L576

It would be useful for this to be configurable. For example, saving PNGs would make it a little more user-friendly in terms of being able to right-click > save as the image.

**Comment by antonkulaga** [comment]
I would be totally happy with svg output if polynote will check the cells output and generate a save button for each of the svg-s there
