### ISSUE TITLE
kill kernel button doesn't always work as advertised

### ISSUE THREAD

**Issue by indig** [polynote/polynote#104]
Need to investigate why that might be. 

The scope of this issue might be very broad. I propose some investigation to see how much work it might be to really clear all the state out - it might turn out to be something simple or it might end up needing #101 to really be done right. 

If it's simple we can try to solve it for alpha, but if it ends up being tricky we can disable the button in the UI for alpha and punt on this issue until beta.

**Comment by jeremyrsmith** [comment]
This may or may not be a current issue... investigate and see if it works or not, and when it doesn't.

**Comment by indig** [comment]
While working on #143 I killed and restarted the kernel a bunch of times and didn't see any problems, so I'll go ahead and close this.
