### ISSUE TITLE
Allow hyperlinks in a Text cell

### ISSUE THREAD

**Issue by faisalzs** [polynote/polynote#106]
Often it's useful to have hyperlinks pointing to other doc or notebook in a Text cell describing what we are are going to do in a subsequent code cell. It will be great to have the ability to hyperlink any arbitrary text much like google docs

**Comment by jeremyrsmith** [comment]
This would really just need a UI (underlying markdown is already supported). I'd punt this to the point when we replace the RTE (#12), as it will fix this too

**Comment by indig** [comment]
Agreed, set this to the beta milestone
