### ISSUE TITLE
cells created with hotkeys fail into funny state

### ISSUE THREAD

**Issue by aviatesk** [polynote/polynote#1130]
**Description**

Code can't be executed in cells created with hotkeys

**Reproduction**
1. create a cell with <kbd>ctrl-cmd-b</kbd>
2. enter `spark`, and run it
3. will yield the following error:
   ```
   Errornot found: value sparkkraps (Line 0,0)
   ```

**Environment**
Are you using the official Docker distribution? If so, please provide your `docker run` command and any other details that may be relevant (mount points, etc). 

Otherwise, please provide the following information:
- Polynote Version: 0.4.0
- Operating System: Mac OS Mojave 10.14.6
- JVM Version: 1.8.0_212
- Python Version: 3.8.0
- How you installed Polynote: I downloaded this release https://github.com/polynote/polynote/releases/download/0.2.12/polynote-dist.tar.gz and then followed [these instructions](https://polynote.org/docs/01-installation.html).
- The command you are using to start Polynote: `./polynote.py`

**Configuration**
If applicable, please attach or paste your Polynote configuration (`config.yml`)

**Notebook**
If applicable, please attach or paste the notebook file (`.ipynb`) you were trying to run when you see this bug. 

**Logs**
If applicable, please attach or paste the Polynote log

**Screenshots**

![image](https://user-images.githubusercontent.com/40514306/113546838-bfc23980-9627-11eb-9eb9-223a0de20dda.png)

**Additional context**

I confirmed a cell created via GUI can be executed as expected.

**Comment by jonathanindig** [comment]
Hi @aviatesk, thanks for the report! We're looking into this.
