### ISSUE TITLE
Spark properties should be trimmed

### ISSUE THREAD

**Issue by jeremyrsmith** [polynote/polynote#1172]
Currently it's easy to accidentally have a space after a spark configuration property, which leads to e.g. that property not properly overriding the same property from the template. For example, configuring `spark.driver.memory ` (notice the space at the end) won't work.

We should ensure these are all trimmed of leading/trailing whitespace.

**Comment by jonathanindig** [comment]
Hmm, we had this issue before https://github.com/polynote/polynote/issues/497. Regression?

**Comment by jeremyrsmith** [comment]
I guess so?

**Comment by omidmogasemi** [comment]
I can't seem to reproduce this in production (I also double checked each text box used in the file). Going to mark this as completed for now.
