### ISSUE TITLE
Support for environment variables

### ISSUE THREAD

**Issue by nragon** [polynote/polynote#1173]
**Description**
All configuration parameters set on config.yml should be also possible to be set using environment variables.
Ex.: 
listen:
  host: 127.0.0.1
  port: 8192

LISTER_HOST=127.0.0.1
LISTEN_PORT=8192

**Comment by jonathanindig** [comment]
Hi @nragon, can you expand on the use case for this? 

You can use something like [`envsubst`](https://linux.die.net/man/1/envsubst) if your deployment requires configurability using environment variables. Would that work for you?
