### ISSUE TITLE
Polynote version 0.4.1 doesn't seem to be working with Java 16

### ISSUE THREAD

**Issue by sipah00** [polynote/polynote#1177]
**Description**
I followed the installation guide here: https://polynote.org/docs/01-installation.html to install `polynote`, but on running `./polynote.py` it gives the following error:
```
[INFO]   Polynote version 0.4.1
[INFO]   Server listening on http://localhost:8192/
Fiber failed.
An unchecked error was produced.
java.lang.IllegalAccessError: class polynote.server.Server$MimeTypes$ (in unnamed module @0x2eb231a6) cannot access class sun.net.www.MimeTable (in module java.base) because module java.base does not export sun.net.www to unnamed module @0x2eb231a6
    at polynote.server.Server$MimeTypes$.<init>(Server.scala:221)
    at polynote.server.Server$MimeTypes$.<clinit>(Server.scala)
```

**Java Version**
```bash
(base) ➜  ~ java -version
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment Homebrew (build 16.0.1+0)
OpenJDK 64-Bit Server VM Homebrew (build 16.0.1+0, mixed mode, sharing)
(base) ➜  ~
```

**Environment**
- Polynote Version: 
   - 0.4.1
- Operating System: 
  - Mac OS Catalina 10.15.7
- JVM Version:
  - 16.0.1
- Python Version:
  - 3.9.1
- How you installed Polynote: 
  - I downloaded this release https://github.com/polynote/polynote/releases/download/0.2.12/polynote-dist.tar.gz and then followed [these instructions](https://polynote.org/docs/01-installation.html).
- The command you are using to start Polynote:
  - `./polynote.py`

**Comment by edbrasil** [comment]
Any luck? I'm having the same issue.

**Comment by kuckjwi0928** [comment]
Need to fix the https://github.com/polynote/polynote/blob/master/polynote-server/src/main/scala/polynote/server/Server.scala

If you modify it like below it will work

`MimeTable.getDefaultTable` to `URLConnection.getFileNameMap`

I guess it related to JPMS(Java Platform Module System)

**Comment by jeremyrsmith** [comment]
Thanks for the note @kuckjwi0928, in fact I had already applied the same fix in this branch: https://github.com/polynote/polynote/pull/1201.

**Comment by jeremyrsmith** [comment]
(I'm still not sure that everything will work fine with Java 16, though – I can't easily test against it. So even when that's merged, I'll leave this issue open until someone confirms that it works)

**Comment by kuckjwi0928** [comment]
@jeremyrsmith 
When will [1201](https://github.com/polynote/polynote/pull/1201) PR be merged?
