### ISSUE TITLE
Unable to use delta or SQL commands

### ISSUE THREAD

**Issue by ahmednrana** [polynote/polynote#1178]
**Description**
Unable to use delta lake to write to disk
**Reproduction**
1. Use WSL2
2. Run this 
```
val data = spark.range(0, 5)
data.write.format("delta").save("/data/delta-table")
```
The w

**Environment**
I tried docker distribution somehow it doesnot open the UI. So I installed it on WSL2. 

Otherwise, please provide the following information:
- Polynote Version: 
   - Example: 0.4.2
- Operating System: 
  - Windows 10
 

**Configuration**
If applicable, please attach or paste your Polynote configuration (`config.yml`)
I uncommented this 
```
listen:
  host: 0.0.0.0
  port: 8192
```

**Notebook**
If applicable, please attach or paste the notebook file (`.ipynb`) you were trying to run when you see this bug. 
```
val data = spark.range(0, 5)
data.write.format("delta").save("/data/delta-table")
```

**Logs**
If applicable, please attach or paste the Polynote log
It throws this error
_Uncaught exception: java.net.ConnectException: Call From LAPTOP-EPCAOEUQ/127.0.1.1 to localhost:9000 failed on connection exception: java.net.ConnectException: Connection refused; For more details see: http://wiki.apache.org/hadoop/ConnectionRefused (java.util.concurrent.ExecutionException)_

**Comment by jonathanindig** [comment]
It sounds like you're running into an issue with WSL, see https://github.com/polynote/polynote/issues/671#issuecomment-557159395

Are you sure it's related to delta lake? Does saving in another format (e.g., parquet, json...) work?

**Comment by adrian-saracila** [comment]
@jonathanindig
For delta tables to be read/write, the config("spark.sql.extensions", "io.delta.sql.DeltaSparkSessionExtension") should be provided when a SparkSession is created (see https://docs.delta.io/latest/quick-start.html).
Once the config added, the SQL statements like 'select * from delta_table' throws errors.
Also, the SQL against another formats also does not work with the above config.
Without it, the SQL against another format is working ok.

Error message:
    Uncaught exception: loader constraint violation: when resolving method "org.apache.spark.sql.catalyst.parser.ParserUtils$.withOrigin(Lorg/antlr/v4/runtime/ParserRuleContext;Lscala/Function0;)Ljava/lang/Object;" the class loader (instance of polynote/kernel/util/LimitedSharingClassLoader) of the current class, io/delta/sql/parser/DeltaSqlAstBuilder, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for the method's defining class, org/apache/spark/sql/catalyst/parser/ParserUtils$, have different Class objects for the type org/antlr/v4/runtime/ParserRuleContext used in the signature (java.lang.LinkageError)

        io.delta.sql.parser.DeltaSqlAstBuilder.visitSingleStatement(DeltaSqlParser.scala:187)
        io.delta.sql.parser.DeltaSqlAstBuilder.visitSingleStatement(DeltaSqlParser.scala:142)
        io.delta.sql.parser.DeltaSqlBaseParser$SingleStatementContext.accept(DeltaSqlBaseParser.java:149)
        org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
        io.delta.sql.parser.DeltaSqlParser.$anonfun$parsePlan$1(DeltaSqlParser.scala:70)
        io.delta.sql.parser.DeltaSqlParser.parse(DeltaSqlParser.scala:99)
        io.delta.sql.parser.DeltaSqlParser.parsePlan(DeltaSqlParser.scala:69)
        org.apache.spark.sql.SparkSession.$anonfun$sql$2(SparkSession.scala:616)
        org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:111)
        org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:616)
        org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
        org.apache.spark.sql.SparkSession.sql(SparkSession.scala:613)
        polynote.kernel.interpreter.sql.SparkSqlInterpreter.$anonfun$run$8(SparkSqlInterpreter.scala:43)
        zio.internal.FiberContext.evaluateNow(FiberContext.scala:490)
        zio.internal.FiberContext.$anonfun$evaluateLater$1(FiberContext.scala:775)
        polynote.kernel.interpreter.CellExecutor$$anon$1.$anonfun$run$2(CellExecutor.scala:33)
        scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        scala.Console$.withOut(Console.scala:167)
        polynote.kernel.interpreter.CellExecutor$$anon$1.$anonfun$run$1(CellExecutor.scala:33)
        scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        polynote.kernel.package$.withContextClassLoader(package.scala:95)
        polynote.kernel.interpreter.CellExecutor$$anon$1.run(CellExecutor.scala:31)
        java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        java.lang.Thread.run(Thread.java:748)

**Comment by jeremyrsmith** [comment]
This looks like the same issue as #946?

**Comment by adrian-saracila** [comment]
Yes, same issue, first reported by user ludovicc.
