### ISSUE TITLE
Unable to mount volumes that contains symlink

### ISSUE THREAD

**Issue by shangqing-li** [polynote/polynote#1184]
**Description**

I am trying to mount AWS EFS volume to Polynote server, and the volume directory that I am trying to mount contains symlinks (some symlinks are circular) or empty sub-directory (they are empty on purpose). I am running into 3 issues below:

1. Empty sub-directory does not show up
2. Unable to mount the volume that contains symlink
3. Thrown error for circular symlinks `java.io.UncheckedIOException: java.nio.file.FileSystemLoopException: `

I am wondering if mounting volumes that contain symlinks/empty folders is supported by Polynote.

**Reproduction**
1. Mount volume containing symlink
2. Start polynote server

**Environment**
Are you using the official Docker distribution? If so, please provide your `docker run` command and any other details that may be relevant (mount points, etc). 

Otherwise, please provide the following information:
- Polynote Version: 0.3.10
- Operating System:  Linux Ubuntu 18.04
- JVM Version: 1.8.0_292
- Python Version: 3.7
- How you installed Polynote: 
  - Example: I downloaded this release https://github.com/polynote/polynote/releases/download/0.2.12/polynote-dist.tar.gz and then followed [these instructions](https://polynote.org/docs/01-installation.html).
- The command you are using to start Polynote: `./polynote.py`
- Any other details that might be useful, such as whether you are running Polynote as a service, using a custom script, etc.  

**Configuration**
If applicable, please attach or paste your Polynote configuration (`config.yml`)

```
listen:
  host: 0.0.0.0
  port: 8192
storage:
  dir: notebooks
  mounts:
    efs:
      dir: /efs/home/user
```

**Notebook**
If applicable, please attach or paste the notebook file (`.ipynb`) you were trying to run when you see this bug. 

**Logs**
If applicable, please attach or paste the Polynote log

**Screenshots**
If applicable, please attach screenshots to help explain your problem.

**Additional context**

**Comment by jeremyrsmith** [comment]
> some symlinks are circular

This seems like it might be the problem 😬 I'm not sure what we could do about it. We have to rely on Java at the end of the day, to do filesystem things.

**Comment by jonathanindig** [comment]
Note that `mount` is just a convenience thing for UX, nothing is really "mounted". So if you already have symlinks, you don't really need mounts - you can just make a symlink to `/efs/home/user` from within your `notebooks` directory and it should work, I think. 

If you get the `FileSystemLoopException` when you do that then like @jeremyrsmith said, sounds like a Java issue with circular symlinks... 

We can take a look at the error in more detail if you provide the stack trace, otherwise it's pretty hard to diagnose the problem.
