### ISSUE TITLE
Spark session closed after leaving Polynote server running

### ISSUE THREAD

**Issue by shangqing-li** [polynote/polynote#1185]
I am hosting Polynote server on docker (Linux Ubuntu 18.04) and created Spark session through my Polynote notebook. After leaving the notebook server running for several days (Spark sessions are idle throughout this time), I found that the Spark sessions that I created previously get closed. 

Is this caused by Polynote's garbage collection mechanism? If so, can we configure the life-time for Spark sessions created through Polynote?

**Comment by jeremyrsmith** [comment]
I think this is more likely to do with your Spark environment. Polynote certainly doesn't close Spark sessions without being instructed to.
