### ISSUE TITLE
Unable to create new notebook server using current master branch

### ISSUE THREAD

**Issue by shangqing-li** [polynote/polynote#1205]
**Description**

Trying to build Polynote from `master` branch and run locally on my laptop. I am unable to create new notebooks with the error trace shown in the logs section below.

**Reproduction**
1. `sbt dist` from latest master branch
2. run Polynote on mac os big sur
3. create new notebook

**Environment**
Are you using the official Docker distribution? If so, please provide your `docker run` command and any other details that may be relevant (mount points, etc). 

Otherwise, please provide the following information:
- Polynote Version: built from master branch
- Operating System: Mac OS BigSur 11.6
- JVM Version: 1.8
- Python Version: 3.9
- How you installed Polynote:  built the project from latest master branch
- The command you are using to start Polynote:
  - Example: `./polynote.py`
- Any other details that might be useful, such as whether you are running Polynote as a service, using a custom script, etc.  

**Configuration**

I used default config without customization.

**Notebook**
If applicable, please attach or paste the notebook file (`.ipynb`) you were trying to run when you see this bug. 

**Logs**

```
[ERROR]   (Logged from SocketSession.scala:77)
   |     java.nio.file.NoSuchFileException: /Users/polynote/target/dist/polynote/notebooks/test.ipynb
   |     sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
   |     sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
   |     sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
   |     sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
   |     java.nio.file.Files.newByteChannel(Files.java:361)
   |     java.nio.file.Files.newByteChannel(Files.java:407)
   |     java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
   |     java.nio.file.Files.newInputStream(Files.java:152)
   |     polynote.server.repository.fs.LocalFilesystem$$anonfun$readPathAsString$1.apply(LocalFilesystem.scala:22)
   |     polynote.server.repository.fs.LocalFilesystem$$anonfun$readPathAsString$1.apply(LocalFilesystem.scala:22)
   |     zio.internal.FiberContext.evaluateNow(FiberContext.scala:490)
   |     zio.internal.FiberContext.zio$internal$FiberContext$$run$body$2(FiberContext.scala:775)
   |     zio.internal.FiberContext$$anonfun$29.run(FiberContext.scala:775)
   |     java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   |     java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   |     java.lang.Thread.run(Thread.java:748)
```

**Screenshots**
If applicable, please attach screenshots to help explain your problem.

**Additional context**

**Comment by omidmogasemi** [comment]
Hi @shangqing-li! Are you still having this issue? We've recently updated our documentation for Polynote, please let us know if this issue still persists.
