### ISSUE TITLE
Illegal cyclic reference involving value Out error

### ISSUE THREAD

**Issue by jonathanindig** [polynote/polynote#122]
Tried referencing out and got the above error

<img width="1149" alt="screen shot 2019-03-08 at 10 47 16 am" src="https://user-images.githubusercontent.com/5430417/54048830-b0920880-418f-11e9-98ac-917a0dbfc3c6.png">

**Comment by indig** [comment]
Also in the screenshot we can see that the output of Out is cut off - I guess that's because its a `TinyString`. Should we consider allowing a `ShortString` instead?

**Comment by jeremyrsmith** [comment]
This works now
