### ISSUE TITLE
Release tag question

### ISSUE THREAD

**Issue by chenrui333** [polynote/polynote#1227]
👋 it looks like all the releases were marked as `pre-release`, is there any specify reason of doing it?

Context is I am trying to [upgrade the homebrew formula](https://github.com/Homebrew/homebrew-core/pull/91198) to use the latest release build, but run into some concern with the `pre release` tag.

**Comment by jonathanindig** [comment]
Hi @chenrui333, there were a couple of previous versions which we forgot to mark as `pre-release` which we fixed. What is your concern with this tag?
