### ISSUE TITLE
binascii.cpython-38-x86_64-linux-gnu.so: undefined symbol: PyFloat_Type

### ISSUE THREAD

**Issue by antonkulaga** [polynote/polynote#1238]
When I try to use pip-installed polars library in polynote I get binascii.cpython-38-x86_64-linux-gnu.so: undefined symbol: PyFloat_Type
Same library runs well locally ( Linux Mint 20.3, python 3.10). I think it has something to do with JEP configuration inside polynote [binascii.cpython-38-x86_64-linux-gnu.so: undefined symbol: PyFloat_Type](https://github.com/ninia/jep/issues/206)
![image](https://user-images.githubusercontent.com/842436/150658045-9a29a435-c49e-4ec3-b3f4-0c08f1f0d4e4.png)

**Comment by jonathanindig** [comment]
![image](https://user-images.githubusercontent.com/5430417/150658777-fbf1c7a3-3349-43a9-a62e-1e127f11793c.png)

Works for me with Python 3.7.12. Does that work for you? (Polynote [officially supports Python 3.7](https://polynote.org/latest/docs/installation/#python-support))

**Comment by antonkulaga** [comment]
Python 3.7 is ancient, I usually run python 3.9 or 3.10 in most of my projects. I will try to downgrade to 3.7 or 3.8 and will let you know.

**Comment by jonathanindig** [comment]
We'd love to provide support for newer Python versions, but unfortunately we don't have the bandwidth to do so. 

Please feel free to contribute - as a long time Polynote user it would be great to have your support!

**Comment by jeremyrsmith** [comment]
@antonkulaga Can you try this from ipython inside of a virtualenv (similar to what Polynote would be doing)? It looks like the virtualenv might have something to do with it.

**Comment by omidmogasemi** [comment]
Hey @antonkulaga! Following up to see if you're still having this issue or had tried Jeremy's advice. If not, we will close this issue. Thanks!
