### ISSUE TITLE
Question: Until when will polynote support Scala 2.11?

### ISSUE THREAD

**Issue by i10416** [polynote/polynote#1247]
According to CHANGELOG, polynote starts supporting Scala 2.13 recently(since 0.4.3). 
In addition, now that Spark supports Scala 2.13, I think dropping Scala 2.11 makes sense and it will make maintenance easier and pave the way for migration to Scala 3. 

It seems that some fundamental tools like Metals plan to drop Scala 2.11 in future release.

> Scala 2.11.12 might not be supported in upcoming versions of Metals

**Comment by jonathanindig** [comment]
Scala 2.11 will be supported until we stop needing to support Spark 2.1 😅  Likely in 2023, but hopefully earlier!

**Comment by i10416** [comment]
Thanks!
