### ISSUE TITLE
Python error, `Cannot create a consistent method resolution order (MRO)` if a Scala `List` is in scope

### ISSUE THREAD

**Issue by jeremyrsmith** [polynote/polynote#1249]
Jep (or Python) seems to have a problem interfacing with Scala collections. If a Scala `List` is in scope, any Python cell will fail to run with the error:

```
Uncaught exception: <class 'TypeError'>: Cannot create a consistent method resolution order (MRO) for bases HasNewBuilder, GenTraversableLike (jep.JepException)
```

It looks like this is a normal Python error, but it seems like a regression for Jep. We should minimize, report, and maybe try to fix this error upstream in jep.

**Comment by sepiabrown** [comment]
I have the same issue!
I've tried the `Hello Polynote` example and the above error happens!

**Comment by jeremyrsmith** [comment]
See https://github.com/ninia/jep/issues/406 (and https://github.com/ninia/jep/pull/407 is the fix!)
