### ISSUE TITLE
sluggish UI resizing on big notebooks

### ISSUE THREAD

**Issue by jonathanindig** [polynote/polynote#127]
From @faisalzs 
> I loaded a relatively large [Jupyter] notebook [...] Polynote was able to load it but given it also included all the output results (from the original Jupyter run), it seemed to have a very large size - anyway, it resulted in a some really sluggish UI behavior - when I tried to move the left menu width, what is usually very fast, ends up being a stuttering move , with one step every 1-2 seconds.

My guess is that this is ok to postpone to 0.2.0 but we can move it to alpha if we need to.

**Comment by faisalzs** [comment]
okay to push to 0.2

**Comment by jeremyrsmith** [comment]
Is it just the resizing of panels that gets slow? That's pretty easy to fix... if having tons of Monacos slows *everything* down, though, then that would be a bit more effort.

**Comment by jeremyrsmith** [comment]
Should go through the monaco instances and update their layout in a `requestAnimationFrame` instead, to avoid clogging the UI.

Maybe we should even start with only the visible ones...

**Comment by jonathanindig** [comment]
It's a lot better now but still not as good as we'd like it to be

**Comment by jonathanindig** [comment]
Performance seems reasonable right now, we can open another issue if there are any regressions/pathological cases discovered.
