### ISSUE TITLE
Filename missing in error message when "Search" feature fails parsing a notebook file

### ISSUE THREAD

**Issue by zzeekk** [polynote/polynote#1384]
**Description**
If there exists a corrupt notebook file the "Search" feature shows error "Uncaught exception: expected whitespace or eof got 'langua...' (line 194, column 2) (io.circe.ParsingFailure)".
Unfortunately the error doesn't mention the filename, so it's hard to find and correct the file.
Improvement: The error message should include the filename where the parser fails.

**Reproduction**
1. edit a Notebook file on the command line and add additional random characters at the end
2. "Search" for some text in Polynote

**Environment**
- Polynote Version: 0.5.0

**Comment by omidmogasemi** [comment]
Thanks for catching this @zzeekk! I'll try to have a PR out to address this early next week.
