### ISSUE TITLE
Off-by-one line numbers in errors 

### ISSUE THREAD

**Issue by mjren23** [polynote/polynote#1407]
**Description**
Line numbers for both compiler errors and runtime exceptions are 1 less than the actual line number that the error occurs in. 

**Reproduction**
1. Run cell that will produce an error (e.g. reassign a val) 
2. Expected behavior: error message contains line and column number of problematic line. Actual behavior: error message lists line number - 1. 

**Environment**
- Polynote Version: 
   - 0.5.2

**Screenshots**
<img width="1094" alt="Screenshot 2023-08-30 at 1 42 02 PM" src="https://github.com/polynote/polynote/assets/64228557/3f6a6387-7654-4f58-af60-0921dd0617ba">

**Comment by jeremyrsmith** [comment]
Thanks for the report! 0.5.2 has a ton of regressions, unfortunately. We'll be releasing a new version soon – will try to make sure we address this issue.

**Comment by jonathanindig** [comment]
I think this is the case in 0.5.1 too, and that code hasn't been touched for a long time. 

Totally thought it worked but it seems like it's been a bug for a while 😬
