### ISSUE TITLE
Cell currently running indicator

### ISSUE THREAD

**Issue by indig** [polynote/polynote#147]
Users should be able to tell that a cell is running by looking at it (in addition to the running task view)

**Comment by indig** [comment]
I wonder whether we can mirror the task progress bar in the new execution timestamp section underneath the cell. When a cell is running, there's no execution timestamp and instead we see a progress bar. When it finishes, the bar goes away and the execution timestamp comes up.

**Comment by jeremyrsmith** [comment]
👍

**Comment by indig** [comment]
It would be easier to highlight the running cell as currently cell progress bars don't actually do anything but go from 0 to 100.
