### ISSUE TITLE
Cell inconsistently returns StreamingDataRepr or DataRepr depending on execution order

### ISSUE THREAD

**Issue by indig** [polynote/polynote#149]
I have a cell that returns a DataFrame. If it's the first cell of the notebook that I run, it returns a StreamingDataRepr which is nice because that works with the cool table/graph repr view!

However, if it's not the first cell that's run it returns a lowly DataRepr which I can't even see 😢

**Comment by jeremyrsmith** [comment]
I can't seem to reproduce this... got a notebook that shows the issue?

**Comment by indig** [comment]
You'll need to unzip because github doesn't support ipynbs. 
[repro149.ipynb.zip](https://github.com/polynote/polynote/files/2994050/repro149.ipynb.zip)
