### ISSUE TITLE
Undo button

### ISSUE THREAD

**Issue by indig** [polynote/polynote#15]
I accidentally deleted a cell and I want it back 😢

**Comment by indig** [comment]
This probably has overlap with the History feature we want, but I think that undoing a cell deletion should probably be in the MVP while I think we said History can wait.

**Comment by jeremyrsmith** [comment]
👍 totally agree... I think the simplest approach is a global (notebook-level) undo buffer that only tracks things like insert, delete, and config edit. Not sure if we should connect it to meta-Z in the case where you don't have a cell focused, though, because it gets kind of confusing. Button for sure, though.

**Comment by jeremyrsmith** [comment]
So, I was starting on this but I think we need some discussion around the behavior.

If delete a cell, and then edit another cell, and then click "Undo"... should it undo the edits I made? And then if I click it again it undoes the deletion? Or is it only an "Undo" for notebook-level changes (i.e. adding or deleting a cell)?

I'm thinking it should be the former – it would undo cell edits too (even though each cell has its own undo buffer – we'd have to delegate the cell's undo behavior). Anyone have a different opinion @indig @faisalzs ?

**Comment by indig** [comment]
I think there are a couple different ways to think about it. 

Thinking about it modally: 
- Button clicking mode: Creating and deleting cells is done with a button press, so an undo button next to those could be seen as "undo what I did by pressing that button". 
- Editing mode: Editing a cell is done one at a time and using the keyboard, so meta-Z on the keyboard should undo what I just typed in the cell but it shouldn't undo anything in other cells. 
- There are edge cases that don't fit these two modes, such as creating a new cell when you press shift-enter on the last one

Thinking about it globally:
- I know that meta-Z undos stuff, I know that undo buttons undo stuff. Whatever I just did should be undone if I click / press anything that says undo. 
- This fits with what a word processer would do if, say, I delete text, insert an image, write text - undo after that sequence will just undo all those changes even though inserting an image is done by clicking a button on the toolbar.  

I think what IntelliJ does might show a good compromise between the modal and global views:

Consider that I have multiple panes of files open in front of me. Imagine I edit file A, edit file B, and then go back to file A and edit some more. With A selected, undo will revert my two changes to A while leaving B intact - modal behavior based on which cell is selected. However, a refactor operation (e.g., renaming a method) happens globally across files - if I undo on any modified file it will undo the entire refactor globally. 

So perhaps something similar? "Toolbar actions" such as new cells, deleting cells, etc. are "global" actions. If there are any global actions in the global buffer, any undo action (button or meta-Z) would revert those actions. However, once we run out of global actions, undo actions fall back to the local buffer, so e.g., edits of one cell won't be undone when I meta-Z in another cell. 

Followup question - should undo buffers be stored server-side or client-side? When would they be cleared out - when I reload the page, when I wipe local storage, when I stop the server?

**Comment by jeremyrsmith** [comment]
But modally speaking, IntelliJ and Polynote are different. In IntelliJ the "mode" is the file you're editing. The corresponding thing in Polynote is the notebook you're editing. So I'd kind of think it undoes globally within the notebook you're looking at.

I think undo buffers will be client side. You'll lose them if you refresh. I don't think that's totally unexpected behavior, akin to losing undo if you close & reopen IntelliJ.

**Comment by jeremyrsmith** [comment]
OTOH, by the nature of how cells work (and how editing in different fields works on the web in general), meta-Z is already modal to the cell you're in, not to the notebook. So that's a bit of a clash 😞

**Comment by indig** [comment]
It's not obvious to me that intelliJ file is analogous to polynote notebook - I think it can just as easily be file <-> cell depending on your point of view. 

I think one way to think of it is the "Select All" boundary (cmd+A).

**Comment by indig** [comment]
One could think of it like: 
IntelliJ: Project :: Polynote: Notebook
IntelliJ: File :: Polynote: Cell
