### ISSUE TITLE
UI polishing

### ISSUE THREAD

**Issue by indig** [polynote/polynote#151]
Consolidating a few UI bugs that @faisalzs noticed:
- long error messages wrap around
- use AM/PM for execution time
- use larger time units for execution duration (as necessary)

**Comment by jeremyrsmith** [comment]
Edit: "long error messages wrap around" -> "compile errors lose their red boxes"

**Comment by indig** [comment]
+ ReprUI should show "Default" tab by .... default.

**Comment by jeremyrsmith** [comment]
Fixed by #160
