### ISSUE TITLE
Make cell smaller when collapsed

### ISSUE THREAD

**Issue by faisalzs** [polynote/polynote#320]
Polynote editor does code-folding, which is handy for just pasting a giant scorer json in and running it, while hiding all the uninteresting parts of the JSON. 

It would be nice if the cell itself became smaller when I collapse everything in the editor.

**Comment by indig** [comment]
What about the ability to collapse an entire cell? Would that be useful / obviate the need for this feature? Or would you still want the cell to get smaller when you fold code in addition to being able to collapse the cell.

**Comment by jeremyrsmith** [comment]
@indig I think the code editor should still respond to changes in the "rendered" lines of the code. Currently it just uses the literal number of code lines to compute the height. Monaco will probably give us the "rendered" number of lines through some API

**Comment by indig** [comment]
Resolved by #353
