### ISSUE TITLE
Remember Last Scroll Position When Switching Notebook Tabs

### ISSUE THREAD

**Issue by devesh** [polynote/polynote#332]
When I switch from one notebook tab to another, it looks like it tries to scroll to the position the notebook I am switching _from_ was in. Then I have to manually scroll to where I used to be in the notebook I switched _to_.

For some context, there are some utility functions I wrote in an old notebook that I want to copy into my current notebook, and Polynote forgot where I was in that original notebook after I got the utility functions -- maybe there's an even better way to handle this use case.

**Comment by indig** [comment]
Resolved by #340
