### ISSUE TITLE
UI Refactor

### ISSUE THREAD

**Issue by indig** [polynote/polynote#36]
We know we need to do some refactoring to the UI. We can use this issue to keep track of what should be cleaned up so that when we get around to it we can address a bunch of them at once. 

- We should have tests for the UI
- UI.js is pretty big.

**Comment by indig** [comment]
https://github.com/polynote/polynote/pull/34/files?utf8=%E2%9C%93&diff=split&w=1#r256203004

**Comment by jeremyrsmith** [comment]
This is more of a note than an issue, so closing
