### ISSUE TITLE
Kernel sidebar hidden if too many tabs are open

### ISSUE THREAD

**Issue by jonathanindig** [polynote/polynote#391]
We need to close / stack / scroll tabs when there are too many. 

<img width="841" alt="Screen Shot 2019-07-31 at 10 17 58 AM" src="https://user-images.githubusercontent.com/5430417/62233058-96460a80-b37c-11e9-9a45-c5b8ab21254f.png">

**Comment by omidmogasemi** [comment]
Looks like this issue has since been fixed
