### ISSUE TITLE
Replace prompts for create/import notebook with a modal

### ISSUE THREAD

**Issue by jeremyrsmith** [polynote/polynote#406]
Use a nice modal to present these options rather than the different buttons we have.

**Comment by phillyfan1138** [comment]
Not only is the "prompt" ugly it doesn't work when embedding polynote as an iframe.  This is definitely something that needs updating.

**Comment by phillyfan1138** [comment]
I'm interested in contributing for this, I've forked.  I'm not used to client side work without a framework though.
