### ISSUE TITLE
Milestone for alpha-testing

### ISSUE THREAD

**Issue by indig** [polynote/polynote#41]
We should come up with a milestone for when we'd feel comfortable getting the first set of alpha users.

**Comment by indig** [comment]
When we spoke a while back we decided on the following MVC features: 

- Cancel Task in a Cell: #47 
- Concurrent Editing #34 
- Quick start guide #48
- Configurability #10 

We also had a "Stability" section which basically means that these features should generally work for the most common use cases (we can allow for some bugs in edge cases I think). These are the main features and should be generally "done" for an alpha release:
- Auto complete is snazzy
- Scala + Python Interop
  - ability to use matplotlib to plot data from Scala might be a good example milestone
  - stretch: add SQL interpreter and interop with that too! #33 
- In general, plotting with matplotlib and vegas should work well
- Symbol Table and State updating correctly
  - stdout updates while cell is running
  - stretch: symbol table updates while cell is running? 
  - Spark progress is visible while the cell is running
  - stretch: symbol table updates based on which cell is selected to reflect the state available to that cell (related to #46)
- Rich text editor works well
- Enforced reproducibility in Scala (already present in v0, also related to #46 )
  - stretch: in Python as well. I think with #39 and #46 this might be feasible
- Dependency management #49 

We also have this milestone to keep track of things as well: https://github.com/polynote/polynote/milestone/1

Once these are complete (or at least "complete enough") we can start getting some alpha users to take a look. 

@jeremyrsmith lmk if this reflects your understanding as well - feel free to edit this comment to update / change things.

**Comment by aishfenton** [comment]
LGTM

**Comment by jeremyrsmith** [comment]
I'll close this since we have the milestones set up. Good reference up there ^^ though
