### ISSUE TITLE
New cells should default to code cells

### ISSUE THREAD

**Issue by jonathanindig** [polynote/polynote#436]
Currently, new cell creation defaults to the cell type of the nearby cell. This can be annoying when the nearest cell is a text cell (which happens when a notebook is first created), since users rarely want two adjacent text cells. 

Proposal is to ignore text cells when deciding on the new cell type. As for when there are no code cells nearby, we can default to `scala` for now (and allow users to set their preferred language in future)

**Comment by jeremyrsmith** [comment]
Fixed
