### ISSUE TITLE
Dependency management feature completeness + bug fixes

### ISSUE THREAD

**Issue by indig** [polynote/polynote#49]
I think we are missing a few features: 

- we probably want some default dependencies to be configurable (related to #10)
- we want to be able to add exclusions

Stretch:
- it would be super-cool to be able to use the uber-jar thing that Jayadev's working on but that's not necessary for an alpha release. 
- would be cool to add Python dependencies (do we need a virtualenv to be present?)

_EDIT: move python deps to stretch_

**Comment by jeremyrsmith** [comment]
Honestly I'm not sure we need python dependency management for 0.1.0.

**Comment by jeremyrsmith** [comment]
(because people are used to manually managing python dependencies for their Jupyter notebooks AFAIK)

**Comment by indig** [comment]
Makes sense, I moved that into the Stretch section. 

I added some stretch goals to this and other issues just have a place to put them without writing too many issues. Once we tackle the main features listed we can turn the stretch goals into their own issues.

**Comment by faisalzs** [comment]
yes, agreed on no python dep work for 0.1.0. Uber jar simplification is a nice to have and I would keep it as a stretch goal

**Comment by indig** [comment]
@faisalzs reported that the cancel button duplicates existing dependencies in the UI. Figured I'd fold that bug into this issue.

**Comment by indig** [comment]
+ Visual confirmation of loaded dependencies

**Comment by indig** [comment]
+ better dependency loading error reporting

**Comment by indig** [comment]
> @faisalzs reported that the cancel button duplicates existing dependencies in the UI. Figured I'd fold that bug into this issue.

This has been resolved by #74

**Comment by indig** [comment]
Fixed by #130 #126 #74
