### ISSUE TITLE
Python cell type is shown twice

### ISSUE THREAD

**Issue by nadenf** [polynote/polynote#525]
When installing Polynote for the first time it shows the following cell types in the dropdown:

- Python
- Text
- Python
- Scala
- SQL
- Vega spec

I don't believe Python should be shown twice.

**Comment by jeremyrsmith** [comment]
Is this also with Safari? Or is it with Chrome/Chromium?

**Comment by baank** [comment]
This is only with Chrome(77.0.3865.120) on OSX.

**Comment by jonathanindig** [comment]
Thanks for the report, @baank. Can you please share a screenshot of what you're seeing?

**Comment by omerlevran** [comment]
So this is more of an issue that the selector is showing the current selection + the list 
* From the css it seems like the tool-group is showing up and the cell-language dropdown open 

Side note: Is there documentation to setting up development environment so people can contribute to the project aka fix this bug

![image](https://user-images.githubusercontent.com/8962170/67630115-7b7e1780-f83f-11e9-97f3-3cfe93d61b3a.png)
