### ISSUE TITLE
Notebooks are shown twice in the sidebar

### ISSUE THREAD

**Issue by nadenf** [polynote/polynote#526]
When using Polynote for the first time.

Clicking on the Plus button and entering a notebook name results in the notebook being shown twice on the left hand sidebar.

![Screen Shot 2019-10-24 at 5 33 51 pm](https://user-images.githubusercontent.com/657041/67459517-817bc900-f684-11e9-8c57-63f7bd9d4e40.png)

**Comment by jeremyrsmith** [comment]
Is this also with Safari? Or is it with Chrome/Chromium?

From a hunch: when you edit a code cell, do you also get duplicated keystrokes?

**Comment by baank** [comment]
This is only with Chrome (77.0.3865.120) on OSX.

**Comment by jonathanindig** [comment]
This might have been related to the fix in #729 where we weren't properly cleaning up `listenOnceFor` listeners. 

I'll close this for now assuming that's the case, please feel free to reopen if you still see this behavior with v0.2.17 (or later)!
