### ISSUE TITLE
Wrong installation instructions

### ISSUE THREAD

**Issue by shakedel** [polynote/polynote#527]
When following the instructions in https://polynote.org/docs/01-installation.html
the "Run" section says to run the included bash script: `./polynote`.
This causes the following error: 
```
+ cd polynote
polynote: line 4: cd: polynote: Not a directory
+ exit
```

I tried running it from outside the project root directory (`polynote/polynote`) and it works fine.
Either the documentation or the script can be changed for a fix.

**Comment by jeremyrsmith** [comment]
Welcome, thanks for the issue report!

This certainly seems like a bug, although I can't reproduce that behavior. It seems like it must be caused by the line

```
cd "${0%/*}" || exit
```

which is supposed to make sure the CWD is the same directory that the script is located in. Can you tell me what OS and shell you're using? What do you see when you run `/usr/bin/env bash --version`?

**Comment by shakedel** [comment]
1. macOS Mojave 10.14.6
2. zsh
3.
```
> polynote /usr/bin/env bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)
Copyright (C) 2007 Free Software Foundation, Inc.
```

**Comment by dene-latch** [comment]
Not sure if I should open a new issue, or piggy back on this one. Also having trouble with the install and first steps.

macOS Mojave 10.14.6
bash
`/usr/bin/env bash --version`
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)
Copyright (C) 2007 Free Software Foundation, Inc.
Scala code runner version 2.13.1 -- Copyright 2002-2019, LAMP/EPFL and Lightbend, Inc.

I get a polynote server at 
`http://127.0.0.1:8192`
but I cannot evaluate any scala cells

I get
```
scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.

Uncaught exception: object java.lang.Object in compiler mirror not found. (scala.reflect.internal.MissingRequirementError)
```

to reproduce try any of the last four releases, cd to polynote and then run `./polynote`

Also, in your install instructions why do you reference the `polynote.py` script when this is not included in any of the most recent releases?

**Comment by jonathanindig** [comment]
Outdated.
