### ISSUE TITLE
Official distribution via Docker Hub

### ISSUE THREAD

**Issue by MahatmaFatalError** [polynote/polynote#528]
It would be great to have an official release on docker hub.

Currently, there is one, whose officiality is not clear. https://hub.docker.com/r/lolhens/polynote

**Comment by jeremyrsmith** [comment]
Welcome! Thanks for the note!

You're right, that isn't an official docker image (boy, that was quick!) It would be great to have an official docker distribution (maybe with and without Spark?).

**Comment by jeremyalan** [comment]
I'm excited to give polynote a try, but I do prefer Docker for easy cleanup, esp with new tools like this one.  I tried building my own container, or running the community container provided by "lolhens", and both have the same issue.

The command I run:
```
> docker run -p 8192:8192 lolhens/polynote
```

When I go to `http://localhost:8192` in my browser, I get no response.  I did a little digging, and it appears the issue is related to the server binding to 127.0.0.1, instead of 0.0.0.0.

**Comment by jeremyalan** [comment]
... and then I found the `config-template.yml` file, and was able to get it working!

# config.yml
```
listen:
  host: 0.0.0.0
```

If using the community Docker image, this also works:
```
docker run --rm -p 8192:8192 -e "POLYNOTE_CONFIG=listen:\n  host: 0.0.0.0" lolhens/polynote
```

**Comment by jeremyrsmith** [comment]
@jeremyalan

I'd be pretty hesitant about listening on 0.0.0.0 – keep in mind that polynote executes arbitrary code that it receives over the network. Maybe it's OK inside of a docker container, but please make sure that the server isn't externally accessible.

**Comment by ei-grad** [comment]
The command should use `-p 127.0.0.1:8192:8192` to make it only accessible on localhost.

**Comment by ChethanUK** [comment]
> Welcome! Thanks for the note!
> 
> You're right, that isn't an official docker image (boy, that was quick!) It would be great to have an official docker distribution (maybe with and without Spark?).

Both will be good, Separate docker images will be nice.

**Comment by Vilos92** [comment]
I've been maintaining a repo on dockerhub if anyone's interested: https://hub.docker.com/r/greglinscheid/polynote

It handles running polynote on 0.0.0.0 inside the container, and also includes some installations like matplotlib for convenience. There also instructions on mounting your notebooks directory to outside the container, and building your own docker image in the [GitHub repo](https://github.com/Vilos92/polynote).
