### ISSUE TITLE
Specifying Python dep doesn't actually allow me to import it in a Python cell

### ISSUE THREAD

**Issue by zzztimbo** [polynote/polynote#534]
![image](https://user-images.githubusercontent.com/4597/67518867-790e9880-f65a-11e9-9d04-10d85a6c4b65.png)
 
I've run the `import pandas as pd` cell multiple times after the installation is complete and I still get the same error: `Uncaught exception: ModuleNotFoundError: No module named 'pandas' (java.lang.RuntimeException)`

**Comment by zzztimbo** [comment]
![image](https://user-images.githubusercontent.com/4597/67518925-9d6a7500-f65a-11e9-935d-fa9f8e09d441.png)

**Comment by jonathanindig** [comment]
Hi @zzztimbo thanks for the bug report! I see from the other issue that you're using `pyenv` and you were able to get started with the python script from #532, right? 

Are you running that script with your `pyenv` activated? Does it work if you `pip install pandas` and try again?

**Comment by zzztimbo** [comment]
Yes, I'm launching polynote with `python ./polynote.py` with pyenv activated for 3.7.3. I have also activated my virtualenv using Poetry. 

Before I started polynote, I did a `pip list`.

```
Package         Version
--------------- -------
jedi            0.15.1 
jep             3.9.0  
numpy           1.17.3 
pandas          0.25.2 
parso           0.5.1  
pip             19.0.3 
py4j            0.10.7 
pyspark         2.4.4  
python-dateutil 2.8.0  
pytz            2019.3 
setuptools      40.8.0 
six             1.12.0 
virtualenv      16.7.7 
```

I do see the following in the log: 

```
[blaze-selector-4] INFO org.http4s.blaze.channel.nio1.NIO1SocketServerGroup - Accepted connection from /127.0.0.1:50736
Looking in indexes: https://artifactory.tools.earnest.com/api/pypi/earnest-py/simple, https://pypi.org/simple
Requirement already satisfied: numpy in /Users/timchan/.pyenv/versions/3.7.3/lib/python3.7/site-packages (1.16.3)
Looking in indexes: https://artifactory.tools.earnest.com/api/pypi/earnest-py/simple, https://pypi.org/simple
Collecting numpy
  File was already downloaded /Users/timchan/Downloads/polynote/tmp/fooobar.ipynb/venv/deps/numpy-1.17.3-cp37-cp37m-macosx_10_9_x86_64.whl
Successfully downloaded numpy
Looking in indexes: https://artifactory.tools.earnest.com/api/pypi/earnest-py/simple, https://pypi.org/simple
Requirement already satisfied: pandas in /Users/timchan/.pyenv/versions/3.7.3/lib/python3.7/site-packages (0.24.2)
Requirement already satisfied: numpy>=1.12.0 in /Users/timchan/.pyenv/versions/3.7.3/lib/python3.7/site-packages (from pandas) (1.16.3)
Requirement already satisfied: python-dateutil>=2.5.0 in /Users/timchan/.pyenv/versions/3.7.3/lib/python3.7/site-packages (from pandas) (2.8.0)
Requirement already satisfied: pytz>=2011k in /Users/timchan/.pyenv/versions/3.7.3/lib/python3.7/site-packages (from pandas) (2019.1)
Requirement already satisfied: six>=1.5 in /Users/timchan/.pyenv/versions/3.7.3/lib/python3.7/site-packages (from python-dateutil>=2.5.0->pandas) (1.12.0)
Looking in indexes: https://artifactory.tools.earnest.com/api/pypi/earnest-py/simple, https://pypi.org/simple
Collecting pandas
  File was already downloaded /Users/timchan/Downloads/polynote/tmp/fooobar.ipynb/venv/deps/pandas-0.25.2-cp37-cp37m-macosx_10_9_x86_64.whl
Collecting numpy>=1.13.3
  File was already downloaded /Users/timchan/Downloads/polynote/tmp/fooobar.ipynb/venv/deps/numpy-1.17.3-cp37-cp37m-macosx_10_9_x86_64.whl
Collecting pytz>=2017.2
  File was already downloaded /Users/timchan/Downloads/polynote/tmp/fooobar.ipynb/venv/deps/pytz-2019.3-py2.py3-none-any.whl
Collecting python-dateutil>=2.6.1
  File was already downloaded /Users/timchan/Downloads/polynote/tmp/fooobar.ipynb/venv/deps/python_dateutil-2.8.0-py2.py3-none-any.whl
Collecting six>=1.5
  File was already downloaded /Users/timchan/Downloads/polynote/tmp/fooobar.ipynb/venv/deps/six-1.12.0-py2.py3-none-any.whl
Successfully downloaded pandas numpy pytz python-dateutil six
No matplotlib support: No module named 'matplotlib'
```

**Comment by jonathanindig** [comment]
@zzztimbo Sorry we missed following up on this issue. Have you been able to get Polynote to work? 

We've made some changes to the installation / Python interpreter since then which might have fixed the issue, can you please try with the latest Polynote version and let us know whether you're still running into this problem. 

Thanks!

**Comment by unibeck** [comment]
@jonathanindig not OP, but I am having the same issue, but for `matplotlib`, running on 0.2.13. Starting a new kernel I can see in the UI and logs that polynote is downloading and installing `matplotlib`. However, I get the following error:
![image](https://user-images.githubusercontent.com/15289783/70329733-0cb2b780-180a-11ea-9763-2418cbf68144.png)

Relevant logs:
```
...
Requirement already satisfied: matplotlib~=3.0 in ./tmp/usurnos.ipynb/venv/lib/python3.6/dist-packages (from gluonts) (3.1.2)
...
Collecting matplotlib~=3.0
  File was already downloaded /home/hadoop/polynote/tmp/project.ipynb/venv/deps/matplotlib-3.1.2-cp36-cp36m-manylinux1_x86_64.whl
...
Successfully downloaded gluonts matplotlib boto3 python-dateutil pandas numpy holidays ujson tqdm pydantic kiwisolver pyparsing cycler botocore s3transfer jmespath six pytz dataclasses setuptools docutils urllib3
...
Requirement already satisfied: matplotlib in ./tmp/project.ipynb/venv/lib/python3.6/dist-packages (3.1.2)
...
Collecting matplotlib
  File was already downloaded /home/hadoop/polynote/tmp/project.ipynb/venv/deps/matplotlib-3.1.2-cp36-cp36m-manylinux1_x86_64.whl
...
<function __exit_pyspark__ at 0x7f92d734b400>
No matplotlib support: No module named 'matplotlib'
```

Configuration:
![image](https://user-images.githubusercontent.com/15289783/70329659-e7be4480-1809-11ea-9ce4-b13f9ffe7cdb.png)

For some background, I am running this on a single node AWS EMR cluster with Spark. I was not seeing this issue running it locally a few weeks back. Let me know if there is anything I can do to help figure this out!

**Comment by unibeck** [comment]
@jonathanindig Similar to your suggestion above, this fixed it for me:
`pip3 install matplotlib --user`

I can use this workaround in the meantime.

**Comment by jonathanindig** [comment]
Cleaning up old issues. If anyone is running into this problem, please go ahead and create a new issue with details of your environment and Python installation and we'll look into it 😃
