### ISSUE TITLE
Built-in resource instead of download from Internet

### ISSUE THREAD

**Issue by vietvudanh** [polynote/polynote#540]
We have a private cluster which do not have connection to the internet. Therefore some stylesheet like `fontawesome` or `katex` cannot be loaded.
I think this might be the case for some people too. I think these resources should be built-in the binary, not fetch from the Internet.

**Comment by vietvudanh** [comment]
I added the css and js at [my fork](https://github.com/vietvudanh/polynote/commit/eccd2ac37e468981b361216949c4f3b95d24af0a) hope it help sombody.
However this mean that we need to maintain a local copy of the `fontawesome` and `katex`, which is not latest version.

**Comment by jeremyrsmith** [comment]
That's a pretty good point – I had intended for font-awesome as a time-saver during development, to be replaced by real icons at some point. But it's so darn convenient that I never did that. Will see whether they allow packaging it or not.

We should be able to bundle the katex CSS without any trouble. The JS is already bundled in webpack, I think.

**Comment by jeremyrsmith** [comment]
Also, welcome and thanks for the issue report!

**Comment by vietvudanh** [comment]
> Will see whether they allow packaging it or not.

I didn't think about the license problem. But I believe it's ok according their [free license](https://fontawesome.com/license/free)?

And you are right, font-awesome is truly awesome.
