### ISSUE TITLE
Logo placing inside name is slightly confusing

### ISSUE THREAD

**Issue by cormullion** [polynote/polynote#544]
I confess I misread your name, due to this:

<img width="400" alt="Screenshot 2019-10-25 at 11 31 39" src="https://user-images.githubusercontent.com/52289/67565870-50e86d80-f71e-11e9-9aa5-6b0fe9bb1548.png">

This seems a tad better to me?

<img width="400" alt="Screenshot 2019-10-25 at 11 52 30" src="https://user-images.githubusercontent.com/52289/67565828-3ca47080-f71e-11e9-946a-86b66b526250.png">

**Comment by jeremyrsmith** [comment]
I understand that plenty people are confused by the lambda being used as the letter "N" when 
it's a real letter pronounced as "L". I hastily designed the logo (I am emphatically not a designer) a while ago, and that's the basic reason it's not ideal. But, it grew on us over the months and so we kept it for the time being.

We'll eventually revisit the logo (with the help of someone more talented), but I don't think it's a cardinal sin to use the wrong letter for stylistic license in the meantime. 😄 Plenty of people have also said that they like the logo, so FWIW not everyone is bothered by it.
