### ISSUE TITLE
Nicer ReprOf for `Array[Row]`

### ISSUE THREAD

**Issue by jonathanindig** [polynote/polynote#548]
Right now output for an `Array[Row]` just looks like `[Lorg.apache.spark.sql.Row;@65729ad`

**Comment by AlexDvorak** [comment]
Hi, I would like to work on this, would [this](https://github.com/polynote/polynote/blob/d6ba83d2712ad93c0512712a5d1c84de3964b2b1/polynote-runtime/src/main/scala/polynote/runtime/ReprsOf.scala#L33) be where to start?

**Comment by jeremyrsmith** [comment]
@AlexDvorak This would go in `SparkReprs`; you'd want to define an instance of `SparkReprsOf[Array[Row]]`. Thanks for taking it on; join us on gitter if you need help!

**Comment by tmnd1991** [comment]
Hi guys, I took a shot at this in this PR: https://github.com/polynote/polynote/pull/999

I'm kind of lost how to test it, though 😃 Can I have an hint on that?
