### ISSUE TITLE
bind configuration not working

### ISSUE THREAD

**Issue by citarf** [polynote/polynote#550]
I tried to set the bind ip in config.yml and config-template.yml but polynote only started on 127.0.0.1 address.

**Comment by jonathanindig** [comment]
Welcome @citarf and thanks for trying Polynote!

Where did you put the `config.yml` file? Can you show us the contents of your `polynote/` directory? (for example, the output of `ls -l` inside that directory)

Also, can you please post the contents of the `config.yml` file you created? (for example, `cat config.yml`)

**Comment by citarf** [comment]
Hey !
I'm on debian 10 with java 11, currently i'm not using spark. I followed the installation docs and I copied config-template.yml to config.yml and uncommented the host and port lines. I tried with my public ip, local ip and 0.0.0.0.

![image](https://user-images.githubusercontent.com/8773429/67606061-8de54c00-f780-11e9-82d0-43ce7d7eb37e.png)


![image](https://user-images.githubusercontent.com/8773429/67606041-7ad27c00-f780-11e9-8e6f-d1538ae1f439.png)

Thanks for your help

**Comment by jonathanindig** [comment]
Thanks for the info! I think I see the problem: can you try uncommenting `#listen:` in your `config.yml` (it should just be `listen:` without the `#`) and launching Polynote again?

**Comment by citarf** [comment]
My bad ^^' it's work now. 
thanks and sorry for my "issue"

**Comment by citarf** [comment]
I notice something. Your documentation mention #config.yaml but the correct file is #config.yml
With .yaml extension, the config file is ignore.
![image](https://user-images.githubusercontent.com/8773429/67607610-60e76800-f785-11e9-8d23-d575df6a0b89.png)

**Comment by jonathanindig** [comment]
Thanks @citarf for pointing that out! We do have a fix for this but it's not live yet unfortunately.
