### ISSUE TITLE
Add information on Windows support with WSL

### ISSUE THREAD

**Issue by RocketLL** [polynote/polynote#555]
![image](https://user-images.githubusercontent.com/17565570/67618991-2e934480-f831-11e9-9d95-0d280228aad5.png)

Polynote works on Windows with WSL Ubuntu!
Might be worth it mentioning it in the README or website.

**Comment by jonathanindig** [comment]
Welcome @RocketLL, thanks for trying out Polynote and getting it working on Windows, that's great! We'd definitely welcome a PR with Windows instructions :)

**Comment by sho-87** [comment]
@jonathanindig are there any plans for windows support without having to go through WSL?

**Comment by jonathanindig** [comment]
Hi @sho-87, PRs always welcome!

**Comment by ctivanovich** [comment]
@RocketLL I've got the server up and running in WSL 2, but can't seem to connect to it through chrome. Any extra set-up needed beyond the basic instructions?

**Comment by RocketLL** [comment]
@ctivanovich More details would help. Does the server start up normally? Which address are you connecting to?

**Comment by ctivanovich** [comment]
Yeah, it starts up normally, and I connect to the default address of 127.0.0.1:8192. All looks green in the console, no errors, just, page fails to load in the browser, Chrome's `ERR_CONNECTION_REFUSED`.

**Comment by ctivanovich** [comment]
Any updates on this?

**Comment by jeremyrsmith** [comment]
@ctivanovich see #671 – I guess WSL is in a container, so its network is sandboxed; if you listen on `0.0.0.0` then it apparently works.

Also see https://github.com/microsoft/WSL/issues/4338#issuecomment-528979326 – looks like the underlying issue is fixed after WSL build 18970+ (so you wouldn't even need to configure the listen address)
