### ISSUE TITLE
Notebooks by user like JupyterHub

### ISSUE THREAD

**Issue by dmvieira** [polynote/polynote#560]

**Comment by jonathanindig** [comment]
Welcome @dmvieira! Can you provide us a little more information about what you're asking about? I'm afraid I'm not too familiar with jupyterhub. Thanks!

**Comment by dmvieira** [comment]
Jupyterhub is a web server that enables user to spawn your own Jupyter environment. With Jupyterhub we can provide a service that users just go in and use. Perhaps a good strategy is plug Polynote in Jupyterhub as an Spawner. Here is example of how it works:

![jupyterhub](https://user-images.githubusercontent.com/1108613/67688804-2cd49880-f979-11e9-8595-6fc04c76fd7e.png)

It already have a lot of authentication methods and works like a proxy server:

![proxy jupyterhub](https://jupyterhub.readthedocs.io/en/stable/_images/jhub-fluxogram.jpeg)

**Comment by rmissaoui** [comment]
Anyone working on a solution? @dmvieira Do you know how doable is to plug Polynote as a spawner in JupterHub?

**Comment by dmvieira** [comment]
If you already have an docker for Polynote it should be easy... You need to integrate with this Spawner: https://github.com/jupyterhub/dockerspawner By default they're using `jupyter/scipy-notebook:8f56e3c47fec`

There's a [contract to build a Spawner](https://jupyterhub.readthedocs.io/en/stable/reference/spawners.html), but with docker it should be simple
