### ISSUE TITLE
Download button doesn't work on Firefox

### ISSUE THREAD

**Issue by dmvieira** [polynote/polynote#561]
I did a Docker to try faster, but download button doesn't work: https://hub.docker.com/r/dmvieira/polynote

I don't know if it works without docker

**Comment by citarf** [comment]
Hello, 
The Download button works on polynote without docker. 
it download a .ipynb file.

Polynote has not an official docker image yet. please check this issues : https://github.com/polynote/polynote/issues/528
https://github.com/polynote/polynote/pull/529

**Comment by jonathanindig** [comment]
Welcome @dmvieira and thanks for the bug report! What browser are you using? Do you have a notebook open or are you on the Home screen? Do you see any errors in the javascript console after clicking the download button?

**Comment by dmvieira** [comment]
I realize that is a problem with Firefox without console or network error. With google chrome it works fine. I'll rename my issue

**Comment by dmvieira** [comment]
Firefox 69.0.2 on Mac

**Comment by dmvieira** [comment]
I found that you don't use Content-Type header. This header forces download... It's just it... For Jupyter common Content-Type header is **application/x-ipynb+json**

**Comment by dmvieira** [comment]
staticFiles doesn't recognize ipynb format as media type and add no header

**Comment by dmvieira** [comment]
I did a PR correcting this in http4s framework: https://github.com/http4s/http4s/pull/2932

**Comment by jonathanindig** [comment]
The Download button seems to work on Firefox now. If anyone's still running into this issue, feel free to let us know!
