### ISSUE TITLE
Quick plot for pandas dataframes

### ISSUE THREAD

**Issue by akdor1154** [polynote/polynote#562]
Looks like Scala dataframes have a nice quick-view and quick-plot contextual buttons when they are the sole output.
It would be nice to have similar for Pandas dataframes in Python.

P.S. Huge props for opening this up to the world, and for your patience in getting through the subsequent deluge of "issues".

**Comment by jonathanindig** [comment]
Welcome @akdor1154, thanks for your kind words :) I agree, we could definitely use some nicer UI representations for Python data structures like Pandas dataframes. 

In the meantime, PRs welcome!

**Comment by jonathanindig** [comment]
This was resolved in #802 😄
