### ISSUE TITLE
Can't import Tensorflow

### ISSUE THREAD

**Issue by akdor1154** [polynote/polynote#563]
Getting a really strange error trying to import `tensorflow`.
Notebook cell:
`import tensorflow as tf`
Output:
```
    Uncaught exception: ImportError: cannot import name 'executing_eagerly' from 'tensorflow.python.eager.context' (/home/jarrad/opt/polynote/polynote/tmp/ML_Learns.ipynb/venv/lib/python3.7/site-packages/tensorflow_core/python/eager/context.py) (java.lang.RuntimeException)

        <string>.__polynote_run__(<string>:43)
        <ast>.<module>(<ast>:1)
        __init__.py.<module>(/home/jarrad/opt/polynote/polynote/tmp/ML_Learns.ipynb/venv/lib/python3.7/site-packages/tensorflow/__init__.py:98)
        __init__.py.<module>(/home/jarrad/opt/polynote/polynote/tmp/ML_Learns.ipynb/venv/lib/python3.7/site-packages/tensorflow_core/__init__.py:42)
        __init__.py.<module>(/home/jarrad/opt/polynote/polynote/tmp/ML_Learns.ipynb/venv/lib/python3.7/site-packages/tensorflow_core/_api/v2/audio/__init__.py:10)
        gen_audio_ops.py.<module>(/home/jarrad/opt/polynote/polynote/tmp/ML_Learns.ipynb/venv/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_audio_ops.py:11)
        context.py.<module>(/home/jarrad/opt/polynote/polynote/tmp/ML_Learns.ipynb/venv/lib/python3.7/site-packages/tensorflow_core/python/eager/context.py:32)
        __init__.py.__getattr__(/home/jarrad/opt/polynote/polynote/tmp/ML_Learns.ipynb/venv/lib/python3.7/site-packages/tensorflow/__init__.py:50)
        __init__.py._load(/home/jarrad/opt/polynote/polynote/tmp/ML_Learns.ipynb/venv/lib/python3.7/site-packages/tensorflow/__init__.py:44)
        __init__.py.import_module(/usr/lib/python3.7/importlib/__init__.py:127)
        __init__.py.<module>(/home/jarrad/opt/polynote/polynote/tmp/ML_Learns.ipynb/venv/lib/python3.7/site-packages/tensorflow_core/python/__init__.py:140)
```

When I import tensorflow from the virtualenv's python directly it works fine:
```sh
cd /home/jarrad/opt/polynote/polynote/tmp/ML_Learns.ipynb/venv/
. bin/activate
python
>>> import tensorflow as tf
>>>
```

**Comment by citarf** [comment]
Hello !
Have you tried to put tensorflow in the dependencies of the notebook ?

Like this :

![image](https://user-images.githubusercontent.com/8773429/67634567-1ae1ef80-f8be-11e9-8fc4-d82767246fda.png)

**Comment by akdor1154** [comment]
I had added it there, but the install had failed for an unrelated reason and I'd then gone and added it with pip in the virtualenv manually.
On deleting the virtualenv and making sure polynote's own install completed, the import worked again. Thanks for the patient response, closing. :)

**Comment by ravikrindiswathi** [comment]
cannot import name 'context' from 'tensorflow.python.eager' (unknown location) how to solve this kind of error in jupiter notebook

**Comment by aimeedu** [comment]
> cannot import name 'context' from 'tensorflow.python.eager' (unknown location) how to solve this kind of error in jupiter notebook

I have the same problem.

**Comment by jonathanindig** [comment]
Sorry, we can't help you solve this problem on Jupyter. If anyone is running into this issue on a new installation of the latest Polynote server, please feel free to open a new issue.
