### ISSUE TITLE
Boolean Configuration Settings Ignored?

### ISSUE THREAD

**Issue by acharneski** [polynote/polynote#569]
Hello,

I have been testing Polynote (great work btw) and I have been unable to get configuration files to have any effect. Though I am attempting to configure "behavior/dependencyIsolation" this is also reproduced with a configuration setting given in the template ("spark/spark.driver.userClasspathFirst"). After tracing the code, I've isolated the function that seems to misbehave. Here are a couple snippets to demonstrate:

``` scala
require(Json.fromJsonObject(JsonObject.fromMap(Map(
      "behavior" -> Json.fromJsonObject(JsonObject.fromMap(Map(
        "dependencyIsolation" -> Json.fromBoolean(false)
      )))
    ))).as[PolynoteConfig](PolynoteConfig.decoder).right.get.behavior.dependencyIsolation == false)
```

``` scala
require(Json.fromJsonObject(JsonObject.fromMap(Map(
  "spark" -> Json.fromJsonObject(JsonObject.fromMap(Map(
    "spark.driver.userClasspathFirst" -> Json.fromBoolean(false)
  )))
))).as[PolynoteConfig](PolynoteConfig.decoder).right.get.spark.get("spark.driver.userClasspathFirst") == false)
```

The exact repro for my issue is to use this config.yml file:
``` yaml
behavior:
  dependencyIsolation: false
```
Then observe that an isolated classloader is still used, choosing the wrong codepath at [ScalaCompiler.scala:502](https://github.com/polynote/polynote/blob/master/polynote-kernel/src/main/scala/polynote/kernel/ScalaCompiler.scala#L502)

I am running this on Windows 10, launched from IDEA using polynote-embedded (https://github.com/polynote/polynote/pull/558) but I do not suspect those details are related.

**Comment by acharneski** [comment]
Update: This may be only for boolean settings. This code works, demonstrating that the bind IP can be set:
``` scala
require(Json.fromJsonObject(JsonObject.fromMap(Map(
      "listen" -> Json.fromJsonObject(JsonObject.fromMap(Map(
        "host" -> Json.fromString("0.0.0.5")
      )))
    ))).as[PolynoteConfig](PolynoteConfig.decoder).right.get.listen.host == "0.0.0.5")
```

**Comment by jeremyrsmith** [comment]
This is a documentation problem; the setting in YAML is
`dependency_isolation`.

**Comment by acharneski** [comment]
Confirmed, thank you. I checked the other repro snippets I posted, and the second was wrong. The following works:
``` scala
    require(Json.fromJsonObject(JsonObject.fromMap(Map(
      "spark" -> Json.fromJsonObject(JsonObject.fromMap(Map(
        "spark.driver.userClasspathFirst" -> Json.fromBoolean(false)
      )))
    ))).as[PolynoteConfig](PolynoteConfig.decoder).right.get.spark("spark.driver.userClasspathFirst") == "false")
```
Closing this issue as it is not a software bug.
