### ISSUE TITLE
Running Polynote using a proxy (binder)?

### ISSUE THREAD

**Issue by kmader** [polynote/polynote#571]
I was trying to make a self-contained repo2docker repository for running polynote and encapsulating the requirements. The only thing missing would be the ability to add a prefix to the base url to account for the fact it is being proxied (or removing all absolute URL and just using relative). It seems like the ```<base href="/" />``` is the big issue so allowing that to be specified in a config file would solve the issue.

https://github.com/polynote/polynote/blob/c0ee2e0a259a272a28418f7c804b07faf62ade79/polynote-frontend/index.html#L6

https://github.com/kmader/nbpolynote/issues/1

**Comment by arnim** [comment]
To make this run with https://github.com/jupyterhub/binderhub / mybinder.org would be a great way for a larger audience to give this a try.

**Comment by kmader** [comment]
Looks great! I don't have a laptop this weekend but once their is a new release I can test it on binder! Thanks

**Comment by kmader** [comment]
@jeremyrsmith the page seems to immediately refresh to the base url
try: https://mybinder.org/v2/gh/kmader/nbpolynote/add-base-uri?urlpath=%2Fpolynote
and the URL starts (just for my instance) as it should with
https://hub.gke.mybinder.org/user/kmader-nbpolynote-ejn2fotc/polynote/
but then immediately changes to
https://hub.gke.mybinder.org/
and refreshes
Is there something besides `base_uri` which needs to be configured?

Here is the contents of the index.html
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Polynote</title>
    <meta charset="utf-8" />
    <base href="/user/kmader-nbpolynote-ejn2fotc/polynote/" />
    <link rel="stylesheet" type="text/css" href="style/styles.css" />
    <link rel="stylesheet" href="vendor/katex/katex.min.css">
    <script defer src="vendor/katex/katex.min.js"></script>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
  </head>
  <body>
    <div id="Main" data-ws-key="8def23ac-29b9-431b-9d7b-314ad323718b" />
  <script type="text/javascript" src="app.b9a0ed98d07143c4b609.js"></script></body>
</html>
```
