### ISSUE TITLE
polynote not using config.yml settings

### ISSUE THREAD

**Issue by saibalpatra** [polynote/polynote#575]
Updated host and port as per documentation but polynote uses host 127.0.0.1 and port 8192 instead of the ones mentioned in the config file.

**Comment by jeremyrsmith** [comment]
Welcome! Thanks for the issue report!

On startup, Polynote should print a message indicating from where it's reading the configuration. Can you check that it's reading the configuration file that you expect?

**Comment by saibalpatra** [comment]
[INFO]  Loading configuration from config.yml
[zio-default-async-7-395629617] INFO org.http4s.blaze.channel.nio1.NIO1SocketServerGroup - Service bound to address /127.0.0.1:8192
[zio-default-async-7-395629617] INFO org.http4s.server.blaze.BlazeServerBuilder -


  _____      _                   _
 |  __ \    | |                 | |
 | |__) |__ | |_   _ _ __   ___ | |_ ___
 |  ___/ _ \| | | | | '_ \ / _ \| __/ _ \
 | |  | (_) | | |_| | | | | (_) | ||  __/
 |_|   \___/|_|\__, |_| |_|\___/ \__\___|
                __/ |
               |___/

[zio-default-async-7-395629617] INFO org.http4s.server.blaze.BlazeServerBuilder - http4s v0.20.6 on blaze v0.14.6 started at http://127.0.0.1:8192/

=======
BUT ...

config.yml has

#listen:
  host: 10.x.x.x
  port: 8081

**Comment by jeremyrsmith** [comment]
Ah, it looks like you need to uncomment the `listen:` line. It should look like:
```
listen:
  host: 10.x.x.x
  port: 8081
```
(note the lack of `#` sign in front of `listen`, which comments it out if present)

**Comment by saibalpatra** [comment]
Thanks @jeremyrsmith

**Comment by saibalpatra** [comment]
Not an issue.
