### ISSUE TITLE
Spark implicits not imported: Value $ is not a member of StringContext + Unable to find encoder

### ISSUE THREAD

**Issue by MehdiFal** [polynote/polynote#577]
Hello, 

Thanks a lot for this very nice piece of software, it was much needed! :)

I deployed Polynote on an EMR Cluster (version 5.27.0 => Spark 2.4.4 built with Scala 2.11.x)

Now I'm facing 2 issues, the second one happening when I work around the first one:

**1- Value `$` is not a member of StringContext:**
Happens when I use the `$` method, even though I include the spark implicits on the same cell. (same code works fine on zeppelin or elsewhere)
```
import spark.sqlContext.implicits._

val myDataSet = rawDataSet.select(
    $"_1".as[CustomRecord], 
    $"_2".as[CustomRecord]
)
```

Then I replace the `$` method by the `col` function, leading to issue 2 below.

**2- Unable to find Encoder for the type `com.mypackage.CustomRecord`**:
This dependency is basically just a `case class` I include from the Polynote UI, then I restart the notebook.
```
import org.apache.spark.sql.functions.{col}
import spark.sqlContext.implicits._
import spark.implicits._

val myDataSet = rawDataSet.select(
    col("_1").as[CustomRecord], 
    col("_2").as[CustomRecord]
)
```

And the full stack trace being:
```
Unable to find encoder for type com.mypackage.CustomRecord. 
An implicit Encoder[com.mypackage.CustomRecord] is needed to store com.mypackage.CustomRecord instances in a Dataset. 
Primitive types (Int, String, etc) and Product types (case classes) are supported by importing spark.implicits._  
Support for serializing other types will be added in future releases.
``` 

Which I don't understand since I don't declare the `CustomRecord` class on the same scope as the Spark app as [this SO question](https://stackoverflow.com/questions/34715611/why-is-the-error-unable-to-find-encoder-for-type-stored-in-a-dataset-when-enco)  suggests it could cause this.

------

I could of course create an encoder myself (which is what I'm currently doing and which works fine), but  the fact is that these 2 imports have no effects:
```
import spark.sqlContext.implicits._
import spark.implicits._
```

------

Any ideas? 

Thank you.

**Comment by jeremyrsmith** [comment]
I think both of these issues are probably because of your `import spark.sqlContext.implicits._`.

You don't need to import those, because Polynote already imports them for you (along with some other Spark stuff, like `org.apache.spark.sql.functions._` and the `DataFrame` type). Importing them again probably causes ambiguous implicits which makes nothing work properly.

**Comment by MehdiFal** [comment]
Hello Jeremy, 
You were right, nice catch. 
Thank you.
