### ISSUE TITLE
Error when try to read json file format.

### ISSUE THREAD

**Issue by ariel201286** [polynote/polynote#588]
When try to read a json file an error is thrown

`spark.read.json("file.json")`

java.lang.ClassCastException: cannot assign instance of org.apache.commons.lang3.time.FastDateFormat to field org.apache.spark.sql.catalyst.json.JSONOptions.dateFormat of type org.apache.commons.lang3.time.FastDateFormat in instance of org.apache.spark.sql.catalyst.json.JSONOptionsInRead at java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(ObjectStreamClass.java:2287) at java.io.ObjectStreamClass.setObjFieldValues(ObjectStreamClass.java:1417) at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2293) at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211) at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069) at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573) at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287) at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211) at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069) at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573) at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287) at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211) at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069) at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573) at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287) at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211) at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069) at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573) at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287) at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211) at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069) at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573) at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431) at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:75) at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:114) at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:83) at org.apache.spark.scheduler.Task.run(Task.scala:123) at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408) at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360) at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748) Driver stacktrace: (org.apache.spark.SparkException)

**Comment by ariel201286** [comment]
I have not any dependency on my notebook. The same code run correctly in spark-shell. I try on polynote 0.2.10.

**Comment by jeremyrsmith** [comment]
Which version of Spark are you using? Does this happen with all JSON files? Where is the JSON file located – on the driver machine, or in HDFS/S3?

**Comment by ariel201286** [comment]
I am using Spark 2.4.4. The error happen on any json file. I am trying in my local machine.

**Comment by mohamedali92** [comment]
I can replicate this issue as well both with csv and json files.
I am using the latest official polynote docker image polynote:0.2.10-2.11-spark2.4

Its worth mentioning that I can read the files into a dataframe just fine; I can print their schema as well.

The problem happens when I use head or show to try and see some rows. I should mention that my files contain a timestamp of this format `2017-09-27T00:00:00.000Z`

**Comment by Kevin-Lee** [comment]
Have you tried reading any JSON? It fails for very simple JSON like this

```scala
import spark.implicits._
val jsonDs = List("""{"name":"Kevin", "id":1}""").toDS
val json = spark.read.json(jsonDs) // error here
json.show
```

Error
```
Uncaught exception: Job aborted due to stage failure: Task 0 in stage 4.0 failed 1 times,
most recent failure: Lost task 0.0 in stage 4.0 (TID 4, localhost, executor driver):
java.lang.ClassCastException: cannot assign instance of org.apache.commons.lang3.time.FastDateFormat
 to field org.apache.spark.sql.catalyst.json.JSONOptions.dateFormat 
 of type org.apache.commons.lang3.time.FastDateFormat
 in instance of org.apache.spark.sql.catalyst.json.JSONOptions at
 java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(ObjectStreamClass.java:2287)
 at java.io.ObjectStreamClass.setObjFieldValues(ObjectStreamClass.java:1417)
...
```

I'm using `polynote/polynote:0.2.11-2.11-spark2.4` Docker image with the following Spark options

```
spark.driver.userClasspathFirst: true
spark.executor.userClasspathFirst: true
```
No extra dependencies.

**Comment by biebiep** [comment]
You cannot use any special spark reader due to the commons-lang3 dependency conflict.

This problem arises both on clusters and locally. Somehow the dependency creeps into the notebook/spark, I suppose.

https://issues.cask.co/browse/CDAP-12742
These guys couldn't figure out why it got included in the project either and solved it by hard-excluding commons-lang3.

**Comment by jeremyrsmith** [comment]
I'm not sure what to say about this... none of our JARs include any apache classes whatsoever. It must be a classloader problem.

**Comment by jeremyrsmith** [comment]
This seems to be fixed by #625 which is now released

**Comment by Kevin-Lee** [comment]
@jeremyrsmith Thanks! 👍

**Comment by zhichao-li** [comment]
Did you guys solve the problem in Polynote 0.2.14? I was facing the same problem with spark 2.4.4 while loading the json file.
