### ISSUE TITLE
You are trying to pass an insecure Py4j gateway to Spark - When using a python cell

### ISSUE THREAD

**Issue by MehdiFal** [polynote/polynote#589]
Hello! 

I upgraded from 0.28 to 0.29 and wanted to try creating / running a Python cell.

However no matter what I write in the python cell I get an exception:
```
Uncaught exception: <class 'ValueError'>: You are trying to pass an insecure 
Py4j gateway to Spark. This presents a security risk. If you are sure you understand and 
accept this risk, you can set the environment variable 'PYSPARK_ALLOW_INSECURE_GATEWAY=1', 
but note this option will be removed in Spark 3.0 (jep.JepException)

/mnt/conda/envs/Python3Env/lib/python3.7/site-packages/pyspark/context.__init__(context.py:127)
<string>.<module>(<string>:10)
jep.Jep.exec(Jep.java:-2)
jep.Jep.exec(Jep.java:478)
polynote.kernel.interpreter.python.PySparkInterpreter$$anonfun$polynote$kernel$interpreter$python$PySparkInterpreter$$registerGateway$1.apply(PySparkInterpreter.scala:128)
polynote.kernel.interpreter.python.PySparkInterpreter$$anonfun$polynote$kernel$interpreter$python$PySparkInterpreter$$registerGateway$1.apply(PySparkInterpreter.scala:94)
polynote.kernel.interpreter.python.PythonInterpreter$$anonfun$jep$1.apply(PythonInterpreter.scala:181)
zio.blocking.Blocking$Service$$anonfun$effectBlocking$1$$anonfun$apply$3.apply(Blocking.scala:133)
zio.blocking.Blocking$Service$$anonfun$effectBlocking$1$$anonfun$apply$3.apply(Blocking.scala:127)
zio.internal.FiberContext.evaluateNow(FiberContext.scala:333)
zio.internal.FiberContext.zio$internal$FiberContext$$run$body$2(FiberContext.scala:602)
zio.internal.FiberContext$$anonfun$7.run(FiberContext.scala:602)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)
```

I'm running a Python3 conda environment, and no SSL on the cluster running on a private network (EMR 5.27.0).

Any idea? 

Thank you.

**Comment by Annalal37** [comment]
Previously my python cell worked well but I met the same prob when I configured spark like this then relaunch my polynote: 
![image](https://user-images.githubusercontent.com/31543446/68071739-585fe480-fdb8-11e9-9d3c-65d90560395f.png)

**Comment by jonathanindig** [comment]
Hi @Annalal37. When you add Spark configuration to Polynote, it will start your session with Spark enabled, as [detailed here](https://github.com/polynote/polynote/blob/master/docs/02-basic-usage.md#using-spark-with-polynote). 

This means that it will attempt to start a PySpark session for you, and thus you will get this error, as detailed in this issue and in #602. If you don't need to use Spark, you can remove that configuration and your Python code will run fine. If you do need to use Spark, you can set the environment variable referred to in the error (`PYSPARK_ALLOW_INSECURE_GATEWAY=1`) until we figure out a way to solve #602.

**Comment by Annalal37** [comment]
Hi Jonathanindig, I set "PYSPARK_ALLOW_INSECURE_GATEWAY=1" but it still gave me same error.
![image](https://user-images.githubusercontent.com/31543446/68559481-26b1e200-0478-11ea-85e1-1982ad95282f.png)

**Comment by jonathanindig** [comment]
@Annalal37 can you see whether #635 solves your problem? It’s available in the current release: https://github.com/polynote/polynote/releases/tag/0.2.13 ?

**Comment by jonathanindig** [comment]
Closing assuming #635 solved the problem. Please feel free to reopen if it didn't. Thanks!
