### ISSUE TITLE
2 examples broken with docker

### ISSUE THREAD

**Issue by andaag** [polynote/polynote#601]
```
docker pull polynote/polynote
Using default tag: latest
latest: Pulling from polynote/polynote
Digest: sha256:ac60fde110260106cccdcc85219e257b43cff731c8df57f4b724a2b7f41ee628
Status: Image is up to date for polynote/polynote:latest
```

Both the Plotting Scala data with Matplotlib and Scala Spark to Pandas are broken.

Scala Spark to Pandas : creates virtual environment and looks like it's installing pandas, but generates the following exception after:
```
Uncaught exception: ImportError: Pandas >= 0.19.2 must be installed; however, it was not found. (java.lang.RuntimeException)
```

Plotting Scala data with Matplotlib:
Doesn't find matplotlib, which is natural because matplotlib isn't in it's list of dependencies.

**Comment by jonathanindig** [comment]
Hi @andaag thanks for the bug report! 

I can confirm that these errors are a combination of missing dependencies and some bugs with our python virtualenv setup.

**Comment by jonathanindig** [comment]
I believe these problems have been addressed in the latest releases. Please feel free to reopen if that's not the case. Thanks!
