### ISSUE TITLE
Port not being released on termination

### ISSUE THREAD

**Issue by JD557** [polynote/polynote#603]
Polynote is not releasing the port on termination, which causes some problems when running it from SBT.

How to reproduce:
* start sbt
* run `polynote-spark/run`
* press `Ctrl+C`
* run `polynote-spark/run` again, this time, it will fail

**Comment by jonathanindig** [comment]
Hi @JD557, I've been cleaning up some old issues and noticed that we missed this one, sorry about that! 😅  

I'm going to close with the assumption that things are pretty different now and at least when I run Polynote in IntelliJ it seems to properly exit and release the port. Please feel free to reopen if you're still running into this problem, and I promise we'll respond in less than 11 months 😉
