### ISSUE TITLE
No available interpreter for sql

### ISSUE THREAD

**Issue by Annalal37** [polynote/polynote#609]
Hi When I tried to use SQL, The cell gave me the below error and it seems that the SQL kernel is not executable for me but Python kernel works well.

Uncaught exception: No available interpreter for sql (java.lang.UnsupportedOperationException)
polynote.kernel.LocalKernel$$anonfun$polynote$kernel$LocalKernel$$getOrLaunch$1$$anonfun$apply$58$$anonfun$apply$59.apply(LocalKernel.scala:188)
polynote.kernel.LocalKernel$$anonfun$polynote$kernel$LocalKernel$$getOrLaunch$1$$anonfun$apply$58$$anonfun$apply$59.apply(LocalKernel.scala:188)
scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
zio.Cause$class.flatMap(Cause.scala:82)
zio.Cause$Fail.flatMap(Cause.scala:386)
zio.Cause$class.flatMap(Cause.scala:87)
zio.Cause$Traced.flatMap(Cause.scala:424)
zio.Cause$class.map(Cause.scala:136)
zio.Cause$Traced.map(Cause.scala:424)
zio.ZIO$MapErrorFn.apply(ZIO.scala:2713)
zio.ZIO$MapErrorFn.apply(ZIO.scala:2711)
zio.internal.FiberContext.nextInstr(FiberContext.scala:710)
zio.internal.FiberContext.evaluateNow(FiberContext.scala:358)
zio.internal.FiberContext.zio$internal$FiberContext$$run$body$1(FiberContext.scala:596)
zio.internal.FiberContext$$anonfun$6.run(FiberContext.scala:596)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

Thanks if someone can help!

**Comment by JD557** [comment]
Based on `polynote-spark/src/main/scala/polynote/kernel/interpreter/SparkInterpreters.scala` and `polynote-kernel/src/main/scala/polynote/kernel/interpreter/CoreInterpreters.scala`.

I think that you need Spark to use the SQL kernel (The frontend doesn't perform any checks for that).

Adding something like `spark.driver.memory`=`2g` in the Spark Config seems to fix that.

How are you launching polynote?

**Comment by Annalal37** [comment]
I launched polynote by excuting polynote.exe in mac and pasted "http://127.0.0.1:8192/" to chrome.

**Comment by Annalal37** [comment]
I configure spark like this and follow this doc: https://towardsdatascience.com/getting-started-with-polynote-netflixs-data-science-notebooks-47fa01eae156 Then it worked for me.
![image](https://user-images.githubusercontent.com/31543446/68071526-411ff780-fdb6-11e9-94b1-8951e7c3eed5.png)

**Comment by Annalal37** [comment]
Hi I was running this to launch polynote: http://127.0.0.1:8192/
And I have put configuration as below then I met the same issue as this task: #589
![image](https://user-images.githubusercontent.com/31543446/68116770-8c611400-ff36-11e9-8752-2013615a1334.png)

**Comment by jeremyrsmith** [comment]
Added #633 instead.
