### ISSUE TITLE
Enabling authentication system 

### ISSUE THREAD

**Issue by sanjaydatasciencedojo** [polynote/polynote#612]
How can we enable the authentication system for Polynote? It seems like it can be accessed by anyone. Does it have the feature like Jupyterhub?

**Comment by jeremyrsmith** [comment]
No, it doesn't have its own authentication system. We run it behind a reverse proxy that integrates with our SSO authentication.

Someday it will have its own authentication mechanism – PRs for this are welcome!

**Comment by sanjaydatasciencedojo** [comment]
@jeremyrsmith Thank you for your response.  Is it suitable to be used with Nginx authentication?

**Comment by sanjaydatasciencedojo** [comment]
@jeremyrsmith I think Jupyterhub is fantastic for deploying scalable. Just like Rstudio we can launch Polynote:

**Comment by dm3ll3n** [comment]
ShinyProxy may be a good tool for this purpose, but I'm running into issues with the setup. More details here: https://github.com/polynote/polynote/issues/579#issuecomment-567773733
