### ISSUE TITLE
Unable to set Spark application name

### ISSUE THREAD

**Issue by b-l-a-c-k-b-e-a-r-d** [polynote/polynote#614]
I am using Polynote 0.2.10 and am unable to set the Spark application name that shows up in YARN.  I have tried setting both of these in the Spark Config for the notebook:

* `sparkSubmitArgs`: `--name MyAppName`
* `spark.app.name`: `MyAppName`

I have tried setting one at a time and setting both.  I see `Polynote 0.2.10-SNAPSHOT session` as the app name.

**Comment by jonathanindig** [comment]
Hi @b-l-a-c-k-b-e-a-r-d that's right, looks like we currently override the app name. 

It should be pretty easy to ensure we don't override the app name (i.e., only set the app name if `spark.app.name` is not already present in the configuration). The app name is being set here: https://github.com/polynote/polynote/blob/master/polynote-spark/src/main/scala/polynote/kernel/LocalSparkKernel.scala#L160

PRs welcome!

**Comment by jonathanindig** [comment]
Resolved by #622
