### ISSUE TITLE
Kernel info toggle disappeared.

### ISSUE THREAD

**Issue by kuckjwi0928** [polynote/polynote#618]
Kernel info toggle disappeared.

Is this the intended function?

Polynote version : `0.2.11`

#### ScreenShots
![2019-11-03 17-49-26 2019-11-03 17_49_53](https://user-images.githubusercontent.com/20429567/68082625-6bc78a00-fe62-11e9-8615-6e7618e6308d.gif)

**Comment by jeremyrsmith** [comment]
No, I don't think it should behave like that. Thanks for the report!

**Comment by kuckjwi0928** [comment]
Thanks for your answer.

Can i fix this bug?

**Comment by jonathanindig** [comment]
Of course! PRs are always welcome :)
