### ISSUE TITLE
Error when installation path contains spaces (Could not find or load main class Files.Exploration.Polynote.polynote.deps.scala-xml_2.11-1.2.0.jar)

### ISSUE THREAD

**Issue by spikerish** [polynote/polynote#619]
After downloading 0.2.9 polynote-dist.tar.gz from https://github.com/polynote/polynote/releases/tag/0.2.9. with all the prerequisites installed. Then followed instructions in https://polynote.org/docs/01-installation.html. Didn't change much on the config.yml not sure if that is whats causing it. Then run polynote.py and got the error.

**Comment by jeremyrsmith** [comment]
Can you paste a terminal session where this error occurs?

**Comment by spikerish** [comment]
@jeremyrsmith , all good now. resolved. path had some spaces that wasnt able to be read when running ./polynote.py that does java -cp... thanks

**Comment by jeremyrsmith** [comment]
If everything fails if you have a space in your path, we should fix that 😄

**Comment by spikerish** [comment]
oh sure nice thanks @jeremyrsmith!
