### ISSUE TITLE
Loading spark configs by default

### ISSUE THREAD

**Issue by alexlipa91** [polynote/polynote#621]
Hi, I modified the config.yml file to have a couple of default spark parameters 

`spark:
spark.driver.memory: 2g
spark.driver.cores: 1`

I would expect that in this case as soon as I reference the variable `spark` in a notebook I get a spark context initiated. However this does not happen and I have to manually type this value in the notebook configuration to make a spark context appear.
Is this supposed to work like this or am I misusing something?

Thanks!

**Comment by b-l-a-c-k-b-e-a-r-d** [comment]
Did you create a new notebook in polynote after you added those settings to the yml?  I noticed the settings are only applied to new notebooks.

**Comment by alexlipa91** [comment]
I did, yes

**Comment by jonathanindig** [comment]
HI @alexlipa91, I'm not quite sure I understand what's going on. 

Polynote will create a SparkSession for you when you launch the kernel for that notebook - [as long as there are some Spark settings in that notebook's config](https://github.com/polynote/polynote/blob/master/docs/02-basic-usage.md#using-spark-with-polynote).

Additionally, after modifying `config.yml` you will need to restart the Polynote server for any changes to take affect. 

Do you see the values you set in the configuration of a newly-created notebook (as @b-l-a-c-k-b-e-a-r-d suggested)? If not, perhaps your config isn't being read properly. In that case, can you show me the output of `cat config.yml`? If what you pasted above are the actual contents of your configuration, I don't think that's valid yaml. You can check your yaml configuration using a [linter](http://www.yamllint.com/).

**Comment by alexlipa91** [comment]
the yaml was incorrect. Fixed it now

`[aliparoti@aliparoti-hadoop-03 ~]$ ruby -ryaml -e "p YAML.load(STDIN.read)" < /opt/polynote-notebook/config.yml
{"storage"=>{"dir"=>"/sparkshell_nfs/polynote-notebooks/aliparoti"}, "repositories"=>[{"maven"=>{"base"=>"https://artifactory.booking.com/maven"}}], "spark"=>{"spark.driver.memory"=>"2g", "spark.driver.cores"=>1}}`

However I still don't see these settings appearing

![image](https://user-images.githubusercontent.com/8805803/68321841-b2b3ba80-00c2-11ea-9ee2-5ab2517934b9.png)

**Comment by alexlipa91** [comment]
I run polynote through supervisorctl...I have the feeling this might be related

**Comment by jonathanindig** [comment]
That sounds reasonable - Polynote needs to know where to find the config.yml file. 

Polynote will look for the config in its current working directory. If `config.yml` isn't there, you can tell Polynote where to find it using `--config /wherever/I/put/the/config.yml`

**Comment by alexlipa91** [comment]
thanks solved it! Good to know about the config param, I haven't seen it before in the docs.
