### ISSUE TITLE
notebook deletion button

### ISSUE THREAD

**Issue by jonathanindig** [polynote/polynote#64]

**Comment by kuckjwi0928** [comment]
@jonathanindig 
I'll do this issue, too!

**Comment by jonathanindig** [comment]
HI @kuckjwi0928, thanks for the offer! As of #623 we do have support for deletion when you right-click on the notebook in the file explorer, so I'm not sure this is necessary any more. 

Do you think it's still useful to add a deletion button?

**Comment by kuckjwi0928** [comment]
@jonathanindig 
I agree with you!

**Comment by jonathanindig** [comment]
Resolved by #623
