### ISSUE TITLE
How to import csv file in spark.

### ISSUE THREAD

**Issue by mdrijwan123** [polynote/polynote#643]
**Description**

Hi, This might be an easy question but still I am getting problems that I am unable to import csv file through spark. 
I checked my current location using os.getcwd() and using that I am giving spark my csv location. Even my location is currect. The error it through when I use python interpreter:
'jep.PyJMethod' object has no attribute 'csv'. 
Please correct me where I am wrong. I am using code:
data = spark.read.csv("/examples/data.csv",header = True, inferSchema=True)

**Environment**
I am not using docker, I have extracted polynote gz file and working on it.

Otherwise, please provide the following information:
- Polynote Version: 
   - Example: 0.2.13
- Operating System: 
  - Example: Ubuntu 18.04
- JVM Version:
  - Example: 1.8.0_212
- Python Version:
  - Example: 3.7
- How you installed Polynote: 
  -I downloaded this release https://github.com/polynote/polynote/releases/download/0.2.13/polynote-dist.tar.gz and then followed [these instructions](https://polynote.org/docs/01-installation.html).

**Comment by jonathanindig** [comment]
Try again with `pysparksession` instead of `spark`. This is a temporary workaround until we have a better solution for Python - apologies for the inconvenience.

**Comment by jonathanindig** [comment]
Resolved in #645
