### ISSUE TITLE
base_uri is immediately refreshes to base URL

### ISSUE THREAD

**Issue by kmader** [polynote/polynote#655]
So URL starts (just for my instance) as it should like (in the 
https://hub.gke.mybinder.org/user/kmader-nbpolynote-ejn2fotc/polynote/
but then immediately changes to
https://hub.gke.mybinder.org/
and refreshes (mentioned in #571)

Click here to run your own demo: https://mybinder.org/v2/gh/kmader/nbpolynote/add-base-uri?urlpath=%2Fpolynote (based on this full self-contained repo in repo2docker format: https://github.com/kmader/nbpolynote/tree/add-base-uri)

Is there something besides `base_uri` which needs to be configured?

Here is the contents of the index.html
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Polynote</title>
    <meta charset="utf-8" />
    <base href="/user/kmader-nbpolynote-ejn2fotc/polynote/" />
    <link rel="stylesheet" type="text/css" href="style/styles.css" />
    <link rel="stylesheet" href="vendor/katex/katex.min.css">
    <script defer src="vendor/katex/katex.min.js"></script>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
  </head>
  <body>
    <div id="Main" data-ws-key="8def23ac-29b9-431b-9d7b-314ad323718b" />
  <script type="text/javascript" src="app.b9a0ed98d07143c4b609.js"></script></body>
</html>
```

**Comment by jeremyrsmith** [comment]
I'm hoping this will be fixed by #650 – if you're able to try out that branch and confirm whether it solves the issue, that'd be great!

**Comment by kmader** [comment]
I'll build it tomorrow and try :+1:

**Comment by kmader** [comment]
works! thanks, should we add a link to binder with try it out?
- notebook with polynote as new kernel option: https://mybinder.org/v2/gh/kmader/nbpolynote/master
- polynote directly: https://mybinder.org/v2/gh/kmader/nbpolynote/master?urlpath=%2Fpolynote

**Comment by jeremyrsmith** [comment]
Awesome, we'll make a release soon that will include the change!

**Comment by kmader** [comment]
I've updated the nbpolynote repository to build polynote from the latest master so it's not strictly necessary to update the releases for this case.
