### ISSUE TITLE
Is it possible to integrate polynote with another netflix project genie?

### ISSUE THREAD

**Issue by yuhuali1989** [polynote/polynote#661]
**Description**
Not Bug, just general question.

**Comment by jonathanindig** [comment]
@yuhuali1989 What sort of integration did you have in mind?

**Comment by yuhuali1989** [comment]
@jonathanindig  It's very kind of you to answer my question. So is it possible for polynote to submit spark job use genie and get result from genie stdout/stderr?

**Comment by jonathanindig** [comment]
We do not integrate with Genie directly. If your `spark-submit` command uses Genie then Polynote can use that. You can feed in additional arguments to `spark-submit` using the `sparkSubmitArgs` spark configuration in Polynote.

**Comment by yuhuali1989** [comment]
@jonathanindig Thank you! I almost get your point. Maybe I need to ask genie how spark-submit use genie directly. In genie open code, I can only use genie to submit spark, but spark-submit can not use genie (Netflix may have their spark branch to implement this feature. )

**Comment by jonathanindig** [comment]
@yuhuali1989 I'm sorry but I'm not a Genie expert so I'm not sure there's much more help I can provide. Polynote does not know anything about Genie. It simply looks for a `spark-submit` command on the `PATH` and has a hook for you to add arguments using `sparkSubmitArgs`. When you run Polynote and launch a kernel, you can see the command line it passes to `spark-submit`. 

If you write your own `spark-submit` command that uses Genie, you can use Polynote with Genie. I was able to find this script in the Genie demo that might be helpful. https://github.com/Netflix/genie/blob/486b744a09325103c24a6bca63015f369018c1f3/genie-demo/src/main/docker/client/example/run_spark_submit_job.py

Maybe you could rename that script to `spark-submit` and modify it to suit your needs.

**Comment by yuhuali1989** [comment]
@jonathanindig Great Idea! Thanks a lot!
