### ISSUE TITLE
Python Cell threw Uncaught exception: <class 'TypeError'>: an integer is required (got type bytes) (jep.JepException)

### ISSUE THREAD

**Issue by Annalal37** [polynote/polynote#662]
**Description**
Python Cell threw Uncaught exception: <class 'TypeError'>: an integer is required (got type bytes) (jep.JepException)

**Reproduction**
1. I launched polynote and start kernel, spark session ran successfully
2. created a python cell -> input below codes -> ran python cell -> show errors
import pandas as pd 
a = 1
print(a)

**Environment**
- Polynote Version: 
   - 0.2.13
- Operating System: 
  - Example: Mac OS Catalina 10.15.1
- java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
- Python Version:
  - Python 3.8.0
- How I installed Polynote: 
  - I downloaded this release https://github.com/polynote/polynote/releases and then followed [these instructions](https://polynote.org/docs/01-installation.html).
- The command I am using to start Polynote:
  - ./polynote.py

**Configuration**
my config.yml file is the same as config-template.yml

**Notebook**
Code:
import pandas as pd 
a = 1
print(a)

**Logs**
Uncaught exception: <class 'TypeError'>: an integer is required (got type bytes) (jep.JepException)
polynote.server.repository.ipynb.JupyterOutput$.toResult(ast.scala:110)
polynote.server.repository.ipynb.JupyterCell$$anonfun$toNotebookCell$2.apply(ast.scala:196)
polynote.server.repository.ipynb.JupyterCell$$anonfun$toNotebookCell$2.apply(ast.scala:196)
scala.collection.immutable.List.map(List.scala:284)
polynote.server.repository.ipynb.JupyterCell$.toNotebookCell(ast.scala:196)
polynote.server.repository.ipynb.JupyterNotebook$$anonfun$55.apply(ast.scala:248)
polynote.server.repository.ipynb.JupyterNotebook$$anonfun$55.apply(ast.scala:248)
scala.Function2$$anonfun$tupled$1.apply(Function2.scala:48)
scala.Function2$$anonfun$tupled$1.apply(Function2.scala:47)
scala.collection.immutable.List.map(List.scala:288)
polynote.server.repository.ipynb.JupyterNotebook$.toNotebook(ast.scala:248)
polynote.server.repository.ipynb.IPythonNotebookRepository$$anonfun$loadNotebook$1$$anonfun$apply$2$$anonfun$apply$4$$anonfun$apply$7.apply(IPythonNotebookRepository.scala:34)
polynote.server.repository.ipynb.IPythonNotebookRepository$$anonfun$loadNotebook$1$$anonfun$apply$2$$anonfun$apply$4$$anonfun$apply$7.apply(IPythonNotebookRepository.scala:33)
zio.ZIO$MapFn.apply(ZIO.scala:2682)
zio.ZIO$MapFn.apply(ZIO.scala:2680)
zio.internal.FiberContext.nextInstr(FiberContext.scala:710)
zio.internal.FiberContext.evaluateNow(FiberContext.scala:325)
zio.internal.FiberContext.zio$internal$FiberContext$$run$body$2(FiberContext.scala:602)
zio.internal.FiberContext$$anonfun$7.run(FiberContext.scala:602)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Screenshots**
![image](https://user-images.githubusercontent.com/31543446/68987806-81787e80-0868-11ea-8bc0-162048238b87.png)

**Comment by jonathanindig** [comment]
Hi @Annalal37 

I think this is related to https://issues.apache.org/jira/browse/SPARK-29536 - unfortunately Spark doesn't support python 3.8 in versions less than 3.8. 

Can you please try running with Python 3.7, or without Spark? I'll close this issue for now but feel free to reopen if you see the same problem with either 3.7 and Spark or 3.8 without Spark.

**Comment by meniluca** [comment]
Can we set Polynote to use a different version? Downgrading from 3.8 to 3.6/7 it's not so straightforward.

**Comment by jonathanindig** [comment]
@meniluca Polynote should pick up whichever `python` is on your `PATH`, which is most likely the one you used to launch polynote with [`polynote.py`](https://github.com/polynote/polynote/blob/master/scripts/polynote.py). 

If you have a specific issue in your environment you'd like some help with it might be easier [to ask questions on Gitter](https://gitter.im/polynote/polynote).

**Comment by meniluca** [comment]
@jonathanindig indeed, I had to use conda and install a new environment with python 3.7 (before I was trying to fix the base python installation in the system, bad idea!). Thank you for your help and sorry for the noise!
