### ISSUE TITLE
Cannot PIP install dependency package through config

### ISSUE THREAD

**Issue by jun-sun** [polynote/polynote#665]
**Description**
I am following 
https://medium.com/@giacomo.vianello/install-polynote-with-conda-9d6ee2f66dab
to set up polynote through conda.
When I try to add dependencies through UI config, it does not work as shown below.
I've tried a few different packages, none of them is available through set up in the config.

Otherwise, please provide the following information:
- Polynote Version: 
   - Example: 0.2.13
- Operating System: 
  - Example: Mac OS Mojave 10.14.5
- JVM Version:
  - Example: 1.8.0_192
- Python Version:
  - Example: 2.7.10
- How you installed Polynote: 
  - Example: I downloaded this release https://github.com/polynote/polynote/releases/download/0.2.13/polynote-dist.tar.gz 
- The command you are using to start Polynote:
  - `./polynote.py`
- Any other details that might be useful, such as whether you are running Polynote as a service, using a custom script, etc.  

**Screenshots**
![Screen Shot 2019-11-15 at 4 41 07 PM](https://user-images.githubusercontent.com/7291636/69004568-6b9ba580-08ca-11ea-883e-9597c6d1cf81.png)

conda list in the environment
![Screen Shot 2019-11-16 at 11 43 28 PM](https://user-images.githubusercontent.com/7291636/69004598-02686200-08cb-11ea-9abb-f23e59c93560.png)

**Comment by jun-sun** [comment]
I am also trying the docker , following https://github.com/polynote/polynote/tree/master/docker
The docker does not work as well
![Screen Shot 2019-11-18 at 9 12 25 AM](https://user-images.githubusercontent.com/7291636/69074206-c96fe080-09e3-11ea-9dc9-4f88a1aee031.png)

**Comment by jeremyrsmith** [comment]
Welcome! Thanks for the report!

I was able to get an error with just `keras` listed as a dependency, but the error I got was about `tensorflow`. Adding `tensorflow` as a dependency made it work. Can you try that?

**Comment by jun-sun** [comment]
Hi @jeremyrsmith, 
It's not just keras. I also tried other packages, i.e. xgboost, snowflake-connector-python and a few others. But I cannot install any pkg through the config.
Install them explicitly in my conda environment works. But just want to know why the config install does not work for me.

**Comment by jonathanindig** [comment]
@jun-sun can you please post what Polynote logs to stdout when you see this error?

**Comment by jonathanindig** [comment]
Also, can you please run this in a Python cell in Polynote and post the output? 
```python
import sys
print(sys.version)
for p in sys.path: 
    print(p)
```

**Comment by jun-sun** [comment]
The stdout when I start a notebook with config settings

```
Server running at http://127.0.0.1:8192
[zio-default-async-26-1291286504] INFO org.http4s.server.blaze.BlazeServerBuilder - http4s v0.20.6 on blaze v0.14.6 started at http://127.0.0.1:8192/
[blaze-selector-1] INFO org.http4s.blaze.channel.nio1.NIO1SocketServerGroup - Accepted connection from /127.0.0.1:53006
[zio-default-async-39-1291286504] INFO org.http4s.server.blaze.Http1ServerStage$$anon$1 - Unknown connection header: 'Upgrade'. Closing connection upon completion.
[blaze-selector-3] INFO org.http4s.blaze.channel.nio1.NIO1SocketServerGroup - Accepted connection from /127.0.0.1:53011
[blaze-selector-2] INFO org.http4s.blaze.channel.nio1.NIO1SocketServerGroup - Accepted connection from /127.0.0.1:53010
[blaze-selector-4] INFO org.http4s.blaze.channel.nio1.NIO1SocketServerGroup - Accepted connection from /127.0.0.1:53013
[INFO]  Deploying with command:
        /anaconda3/envs/polynote/jre/bin/java -cp polynote.jar:/Users/junsun/work/polynote/deps/polynote-runtime.jar:/Users/junsun/work/polynote/deps/polynote-spark-runtime.jar:/Users/junsun/work/polynote/deps/portable-scala-reflect_2.11-0.1.0.jar:/Users/junsun/work/polynote/deps/scala-collection-compat_2.11-2.1.1.jar:/Users/junsun/work/polynote/deps/scala-compiler-2.11.12.jar:/Users/junsun/work/polynote/deps/scala-library-2.11.12.jar:/Users/junsun/work/polynote/deps/scala-reflect-2.11.12.jar:/Users/junsun/work/polynote/deps/scala-xml_2.11-1.2.0.jar -Djava.library.path=/anaconda3/envs/polynote/lib/python3.7/site-packages/jep polynote.kernel.remote.RemoteKernelClient --address 127.0.0.1 --port 53014 --kernelFactory polynote.kernel.LocalKernelFactory
[INFO]  Connected. Decoding incoming messages
```


The output for system path
```
3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 14:42:21) 
[Clang 4.0.1 (tags/RELEASE_401/final)]

/anaconda3/envs/polynote/lib/python37.zip
/anaconda3/envs/polynote/lib/python3.7
/anaconda3/envs/polynote/lib/python3.7/lib-dynload
/Users/junsun/.local/lib/python3.7/site-packages
/anaconda3/envs/polynote/lib/python3.7/site-packages
```

**Comment by jonathanindig** [comment]
@jun-sun Are you clicking `Save & Restart` button before running the cell?

**Comment by jun-sun** [comment]
@jonathanindig 
Yes, 
even tried to restart the notebook from terminal, see the config refreshed correctly, but just unable to find the modules

**Comment by jonathanindig** [comment]
It should definitely work when using the Docker image, so it's interesting that you aren't having any luck with that. Let's try to get it working for you on Docker so we can figure out the problem when there are fewer variables at play - we can then try to see what's going on in your local environment. 

Here are the logs I see in the Docker container, showing the virtual environment setup and dependency download: 

```
[INFO]  Deploying with command:
        /usr/local/openjdk-8/jre/bin/java -cp polynote.jar:polynote.jar:/opt/polynote/deps/scala-library-2.11.12.jar:/opt/polynote/deps/polynote-runtime.jar:/opt/polynote/deps/scala-reflect-2.11.12.jar:/opt/polynote/deps/portable-scala-reflect_2.11-0.1.0.jar:/opt/polynote/deps/scala-xml_2.11-1.2.0.jar:/opt/polynote/deps/scala-collection-compat_2.11-2.1.1.jar:/opt/polynote/deps/polynote-spark-runtime.jar:/opt/polynote/deps/scala-compiler-2.11.12.jar -Djava.library.path=/usr/local/lib/python3.7/dist-packages/jep polynote.kernel.remote.RemoteKernelClient --address 127.0.0.1 --port 35577 --kernelFactory polynote.kernel.LocalKernelFactory
[INFO]  Connected. Decoding incoming messages
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /opt/polynote/tmp/bloop.ipynb/venv/bin/python3
Also creating executable in /opt/polynote/tmp/bloop.ipynb/venv/bin/python
Installing setuptools, pip, wheel...
done.
Collecting keras
  Downloading https://files.pythonhosted.org/packages/ad/fd/6bfe87920d7f4fd475acd28500a42482b6b84479832bdc0fe9e589a60ceb/Keras-2.3.1-py2.py3-none-any.whl (377kB)
... etc ... 
```

You should see these logs too - they should appear when you start running the Python cell as long as the configuration is correctly saved. 

Like @jeremyrsmith mentioned, if you add `keras` as a dependency you'll get a `No module named 'tensorflow'` error, because `keras` does not add `tensorflow` as a dependency (not sure why). If you have both `keras` and `tensorflow` as dependencies, click `Save & Restart`, and then run the cell again you should see tensorflow being installed and then `import keras` should work. 

Are you still having trouble even with the Docker image after installing both packages and saving the configuration before running it? 

If you are still having trouble, can you try running the "Plotting Scala data with Matplotlib" notebook (in the examples folder in the Docker container)? This imports pandas so it's a good test to check whether importing is working or not.

**Comment by jun-sun** [comment]
Problem solved.
Take a look at the docker example, then I noticed that I put all the packages to the resolvers.
Thanks @jeremyrsmith @jonathanindig
