### ISSUE TITLE
Questions about inserting equations

### ISSUE THREAD

**Issue by itechbear** [polynote/polynote#677]
Hello, 

Just wondering, is there any shortcut for inserting equations in a text/markdown cell ? Any shortcut for inserting inline equations ?

**Comment by jonathanindig** [comment]
Hi @itechbear there are no shortcuts for this right now. Feel free to open a PR to contribute one!

**Comment by jeremyrsmith** [comment]
Not quite true, there is Cmd-E (on Mac) which brings up the equation editor at the current location.

**Comment by jonathanindig** [comment]
😄 That'll teach me to answer without checking the code! Thanks @jeremyrsmith
