### ISSUE TITLE
ploynote should enable kerberos support 

### ISSUE THREAD

**Issue by yuanbw** [polynote/polynote#692]
**Description**
ploynote should enable kerberos support in spark-submit

**Configuration**
should provide the "--keytab" "--principal" args in config.yaml when submitting spark jobs when the remote spark cluster is kerberos enabled.

**Comment by jonathanindig** [comment]
If you just need to set arguments for spark submit, you can do that with the `sparkSubmitArgs` key. 

Something like `sparkSubmitArgs: "--keytab foo --principal bar"`

**Comment by jonathanindig** [comment]
Sorry this wasn't documented. I updated the configuration template with this information: https://github.com/polynote/polynote/blob/master/config-template.yml#L114-L124

**Comment by jeremyrsmith** [comment]
@yuanbw I'm going to close this issue as it seems to be solved. Please reopen if not.
