### ISSUE TITLE
Vegas Support

### ISSUE THREAD

**Issue by bryandg** [polynote/polynote#693]
Is it possible to produce in-line [Vegas](https://github.com/vegas-viz/Vegas) plots in polynote? If not, are there any plans to add this functionality?

**Comment by jeremyrsmith** [comment]
Vegas should work out-of-the-box as far as I know.

**Comment by jonathanindig** [comment]
Vegas indeed works out-of-the-box. 

With `org.vegas-viz:vegas_2.11:0.3.11` added as a dependency:

![Screen Shot 2019-12-05 at 4 36 13 PM](https://user-images.githubusercontent.com/5430417/70285735-63be7b00-177d-11ea-818c-c5d92b473ddd.png)

Closing this issue for now. Feel free to reopen if you're running into any Polynote-specific problems using Vegas or if we misunderstood your question. Thanks for using Polynote! 😄
