### ISSUE TITLE
Can't run polynote due to jep issue

### ISSUE THREAD

**Issue by bron70x** [polynote/polynote#697]
**Description**
Hi,
I just installed polynote on mac, it was not an easy process, I bumped here and there.
And at the end, polynote still wont run. I get this jep error:

Uncaught exception: jep.Jep.init(Ljava/lang/ClassLoader;ZZ)J (java.lang.UnsatisfiedLinkError)

I read other thread about this #531 and been following all the steps there .. and still no result.
What I've been trying:
* removed the shebang line at the top of the polynote.py file - do not want this script to be run by #!/usr/bin/env python3 but by the interpreter of our conda environement.
* I ran: EXPORT PYTHONHOME=/anaconda3/envs/polynote
* Ran the script using the activated conda environment's python, python3 polynote/polynote.py
I am using python3 and Chrome.

Help, thanks!

>> pip3 show jep
Name: jep
Version: 3.9.0
Summary: Jep embeds CPython in Java
Home-page: https://github.com/ninia/jep
Author: Jep Developers
Author-email: jep-project@googlegroups.com
License: zlib/libpng
Location: /Users/opt/anaconda3/lib/python3.7/site-packages

**Reproduction**
1. Run python polynote/polynote.py
2. Type any command in code cell, press PLAY button and here comes the error 

**Environment**
Are you using the official Docker distribution? No docker

Otherwise, please provide the following information:
- Polynote Version: 0.2.13-SNAPSHOT
- Operating System: Mac OS Mojave 10.14.4
- JVM Version: build 1.8.0_231-b11
- Python Version:3.7.4
- How you installed Polynote: 
https://github.com/polynote/polynote/releases/download/0.2.12/polynote-dist.tar.gz and then followed [these instructions](https://polynote.org/docs/01-installation.html).
- The command you are using to start Polynote: python3 polynote/polynote.py

**Configuration**

**Notebook**
#!/usr/bin/env python3
import sys
from pathlib import Path
import os

polynote_dir = os.path.dirname(os.path.realpath(__file__))
os.chdir(polynote_dir)

paths = [ Path(p) for p in sys.path if Path(p).exists() ]
jep_paths = [ p.joinpath("jep") for p in paths if p.joinpath("jep").exists() ]

if len(jep_paths) >= 1:
    jep_path = jep_paths[0]
else:
    raise Exception("Couldn't find jep library. Try running `pip3 install jep` first.")

plugins_path = Path(polynote_dir).joinpath("plugins.d")
plugins = []

if plugins_path.exists():
    plugins = list(plugins_path.glob("*.jar"))

deps_path = Path(polynote_dir).joinpath("deps")

if not(deps_path.exists()):
    raise Exception("Couldn't find the deps directory. Are we in the polynote installation directory?")

deps = Path(polynote_dir).joinpath("deps").glob("*.jar")
classpath = "polynote.jar:" + ":".join([ str(d) for d in deps ])
cmd = f"java -cp polynote.jar:{classpath} -Djava.library.path={jep_path} polynote.Main {' '.join(sys.argv[1:])}"
print(cmd)
os.system(cmd)

**Logs**
Uncaught exception: jep.Jep.init(Ljava/lang/ClassLoader;ZZ)J (java.lang.UnsatisfiedLinkError)
jep.Jep.init(Jep.java:-2)
jep.Jep.<init>(Jep.java:278)
jep.SharedInterpreter.<init>(SharedInterpreter.java:56)
polynote.kernel.interpreter.python.PythonInterpreter$$anonfun$mkJep$2$$anonfun$apply$25.apply(PythonInterpreter.scala:495)
polynote.kernel.interpreter.python.PythonInterpreter$$anonfun$mkJep$2$$anonfun$apply$25.apply(PythonInterpreter.scala:484)
zio.internal.FiberContext.evaluateNow(FiberContext.scala:404)
zio.internal.FiberContext.zio$internal$FiberContext$$run$body$2(FiberContext.scala:602)
zio.internal.FiberContext$$anonfun$7.run(FiberContext.scala:602)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
java.lang.Thread.run(Thread.java:835)

**Screenshots**
If applicable, please attach screenshots to help explain your problem.

**Additional context**

**Comment by ulugbekna** [comment]
@endshonme  you probably want to fix the formatting of the issue

Otherwise, I ran into the same issue now trying to run python with the latest released version of polynote as of now. The reproduction steps are the same.

**Comment by endshonme** [comment]
@ulugbekna deleted config file so it looks prettier

**Comment by jeremyrsmith** [comment]
@endshonme did you install jep into your conda environment? The run script should print the command it's using to start Polynote as the first line of output; can you verify that it's passing the correct path to where `libjep.dylib` exists to `-Djava.library.path`?

**Comment by endshonme** [comment]
@jeremyrsmith let me check and revert

**Comment by jonathanindig** [comment]
Closing old issues. If anyone's running into similar issues with the current version of Polynote, please feel free to open a new issue. Thanks!
