### ISSUE TITLE
polynote tries to resolve jep only in pip3

### ISSUE THREAD

**Issue by antonkulaga** [polynote/polynote#700]
A very big part of developers use python from conda and when you install python in conda the pip is actually pip3 (as python3 is selected as a default language). 
In the same time polynote tries to resolve jep with hard-coded pip3 show jep.
It took me some time to figure out the workaround which for me was:
```bash
 ln -s /opt/conda/bin/pip /usr/bin/pip3
```
However, I suggest that you improve your jep resolution so it will be conda-friendly by default.

**Comment by jonathanindig** [comment]
Have you tried running Polynote with `polynote.py` rather than the bash script? It shouldn't need `pip3` in that case I think.

**Comment by jeremyrsmith** [comment]
Yeah, we should remove the bash script from the distribution. It's quite confusing.

Will close this when that's done.

**Comment by forrestwaters** [comment]
If you're using `polynote.py` with python from conda, you'll also likely need to set `LD_PRELOAD` somehow to the shared python lib like the [bash script tries to do](https://github.com/polynote/polynote/blob/master/scripts/polynote#L10). `$PREFIX/lib/libpython3.{6,7,8}.m.so`.

**Comment by jonathanindig** [comment]
The bash script is no longer used.
