### ISSUE TITLE
Pandas dataframe output is illegible

### ISSUE THREAD

**Issue by MarkLyubimov** [polynote/polynote#707]
Hi!

**Description**
Pandas dataframe output is illegible

**Reproduction**
1. Create scala dataframe
2. Turn it into pandas dataframe
3. Get dataframe output with .head() method

**Notebook**
Here I provide commands to reproduce my problem:

`val scalaDF = spark.createDataFrame(List(1,2,3).map(x => (x, x+1 , x+2, x+3, x+5 , x+6, x+7, x+8 , x+9, x+10, x+11 , x+12, x+13, x+14 , x+15, x+16, x+17 , x+18, x+19, x+20 , x+21, x+22)))`
`scalaDF.show()`

<img width="806" alt="Screenshot 2019-12-19 at 18 28 27" src="https://user-images.githubusercontent.com/36645303/71185939-647f0300-228d-11ea-9c1d-cf438684797f.png">

`from pyspark.sql import DataFrame`
`pythonDF = DataFrame(scalaDF, sqlContext)`
`pandaDF = pythonDF.toPandas()`
`pandaDF.head()`

<img width="218" alt="Screenshot 2019-12-19 at 18 28 32" src="https://user-images.githubusercontent.com/36645303/71185964-706ac500-228d-11ea-9f08-9331aa53e2b1.png">

I found an example [here](https://github.com/polynote/polynote/blob/master/docs/examples/Scala%20Spark%20to%20Pandas.ipynb), but my result is different.

Could you help me please?

**Comment by jeremyrsmith** [comment]
Hi,
This is just how pandas formats the output when you have many columns, I think. When you run the example notebook, does the output look the same?

**Comment by MarkLyubimov** [comment]
My output of example notebook differs from yours
<img width="659" alt="Screenshot 2019-12-20 at 15 01 38" src="https://user-images.githubusercontent.com/36645303/71253699-ab2a3700-2339-11ea-8770-e5d02fa62884.png">
<img width="756" alt="Screenshot 2019-12-20 at 15 01 45" src="https://user-images.githubusercontent.com/36645303/71253705-ae252780-2339-11ea-8e69-a9f3cbf1076d.png">

There are no lines separating columns or rows.

**Comment by jonathanindig** [comment]
Resolved by #802
