### ISSUE TITLE
list[String] is not displayed in out

### ISSUE THREAD

**Issue by antonkulaga** [polynote/polynote#710]
I see the in the latest 0.2.14 version of Polyenote when I have List[String] as a result, it does not show me anything in the "out" section until I click "zoom" icon. This behavior is extremely annoying as often the output is very small and I still have to make an additional click.
![no_out_for_list_string](https://user-images.githubusercontent.com/842436/71325933-7dd9b680-24fc-11ea-8e04-f7b1ffb8806b.png)

**Comment by jelmerk** [comment]
at least println(List("one","two","three")) works ...
