### ISSUE TITLE
Allow to exclude/override certain transitive libraries for Scala

### ISSUE THREAD

**Issue by REASY** [polynote/polynote#716]
Some time it is needed to exclude/override certain transitive libraries.  I see `Exclusions` param in `Configuration & dependencies`, but it is probably not what I wanted. In case of SBT,
an [exclusion of transitive dependency](https://www.scala-sbt.org/1.x/docs/Library-Management.html#Exclude+Transitive+Dependencies) looks:
```sbt
libraryDependencies += 
  "log4j" % "log4j" % "1.2.15" exclude("javax.jms", "jms")
```
[Overriding a version](https://www.scala-sbt.org/1.x/docs/Library-Management.html#Overriding+a+version):
```sbt
dependencyOverrides += "log4j" % "log4j" % "1.2.16"
```

**Comment by jeremyrsmith** [comment]
Can you be more specific about how the Exclusions config doesn't do what you want?

To accomplish your first example, it should work to add `javax.jms:jms` to exclusions. To accomplish the second, it should work add `log4j:log4j` to exclusions and add an explicit dependency for the log4j version that you want. If either of those don't work, that would be a bug.

**Comment by jeremyrsmith** [comment]
I'll go ahead and close this – please reopen if you have any issues accomplishing what you want using excludes.
