### ISSUE TITLE
Multi-line strings are not printed correctly

### ISSUE THREAD

**Issue by REASY** [polynote/polynote#717]
**Description**
Multi-line strings are not printed correctly

**Reproduction**
1. Add cell with multiline string and print it
2. Execute that cell
3. Output of multiline string is wrong

**Environment**
- Polynote Version: 0.2.15-SNAPSHOT, Build Commit: 6f50ee109c68fadce873e22ecb294b9bed56bdd
- Operating System: Windows 10 x64 v10.0.18362.535 with WSL Ubuntu 18.04 LTS
- JVM Version: OpenJDK 64-Bit Server VM, 1.8.0_222
- Python Version: Python 2.7.15rc1
- How you installed Polynote: 
  - I downloaded this release https://github.com/polynote/polynote/releases/download/0.2.15/polynote-dist-2.12.tar.gz and then followed [these instructions](https://polynote.org/docs/01-installation.html).
- The command you are using to start Polynote: `./polynote.py`

**Code**
```Scala
println(">>>Multi-line string")
println("""A: 1
    |B: 2
    |C: 3""".stripMargin)

println
println(">>> Manually constructed multi-line string")
println("A: 1\nB: 2\nC: 3")
```

**Notebook**

```json
{
  "metadata" : {
    "config" : {
      "dependencies" : {
        
      },
      "exclusions" : [
      ],
      "repositories" : [
      ],
      "sparkConfig" : {
        
      }
    }
  },
  "nbformat" : 4,
  "nbformat_minor" : 0,
  "cells" : [
    {
      "cell_type" : "code",
      "execution_count" : 1,
      "metadata" : {
        "cell.metadata.exec_info" : {
          "startTs" : 1577867843779,
          "endTs" : 1577867843984
        },
        "language" : "scala"
      },
      "language" : "scala",
      "source" : [
        "println(\">>>Multi-line string\")\r\n",
        "println(\"\"\"A: 1\r\n",
        "    |B: 2\r\n",
        "    |C: 3\"\"\".stripMargin)\r\n",
        "\r\n",
        "println\r\n",
        "println(\">>> Manually constructed multi-line string\")\r\n",
        "println(\"A: 1\\nB: 2\\nC: 3\")"
      ],
      "outputs" : [
        {
          "name" : "stdout",
          "text" : [
            ">>>Multi-line string",
            "\n",
            "A: 1\r\n",
            "B: 2\r\n",
            "C: 3",
            "\n",
            "\n",
            ">>> Manually constructed multi-line string",
            "\n",
            "A: 1\n",
            "B: 2\n",
            "C: 3",
            "\n"
          ],
          "output_type" : "stream"
        }
      ]
    },
    {
      "cell_type" : "code",
      "execution_count" : 2,
      "metadata" : {
        "language" : "scala"
      },
      "language" : "scala",
      "source" : [
      ],
      "outputs" : [
      ]
    }
  ]
}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/5107562/71639805-17008e00-2cb0-11ea-87ca-b971ff301e03.png)

**Comment by jeremyrsmith** [comment]
I wasn't able to reproduce this on Mac or Linux. It would be great if someone with Windows could try and repro.

**Comment by jonathanindig** [comment]
Unable to reproduce - if anyone can reproduce on Windows with the latest version of Polynote, please feel free to reopen. Thanks!
