### ISSUE TITLE
spark.executor.instances: 10 becomes spark.executor.instances: 1e1

### ISSUE THREAD

**Issue by jelmerk** [polynote/polynote#719]
I am using  Polynote Version: | 0.2.15-SNAPSHOT (Build Commit: 36f50ee109c68fadce873e22ecb294b9bed56bdd)

My conf.yaml contains the following lines

```
spark:
  spark.executor.instances: 10
```

When I create a new notebook the value that will be filled in in the config section will be `1e1` instead of `10` which is not a valid value for this

**Comment by jelmerk** [comment]
Looks like this is a "feature" of the most over-engineered json parser known to mankind

`io.circe.yaml.parser.parse(new StringReader("spark:\n  spark.executor.instances: 10"))`

**Comment by jonathanindig** [comment]
Fixed #810
