### ISSUE TITLE
Plotting UI revamp

### ISSUE THREAD

**Issue by jeremyrsmith** [polynote/polynote#725]
The plotting UI leaves a lot to be desired:

* When you bring up the plotting UI, it's not obvious that you have to do some work to make a plot happen. If you don't, there's no error message, just a never-ending wait. (see https://gitter.im/polynote/polynote?at=5e0e36f9eac8d1511e9ed2ff )
* Why do we make you drag things onto axes? Especially when there is only one axis it could go onto (at least for everything but scatter plot, currently).
* `sum` measure is not exposed, even though it's implemented.
* It would be nice to recommend some sane plots off the bat (like https://github.com/vega/voyager – initially tried to integrate this, but couldn't make it build)
* It's just generally buggy, user-unfriendly, and poorly implemented, because it hasn't had much effort put in.

The plotting UI is a pretty self-contained thing that's pretty ripe for a frontend expert to revamp. Making this overarching issue in case anyone wants to have a go at improving the plot editor in any way (from minor enhancement to complete reimplementation – anything would help!)

**Comment by tiffon** [comment]
Seems like 'Help Wanted' might be a better label than 'good first issue'.
