### ISSUE TITLE
Support for Markdown Cells

### ISSUE THREAD

**Issue by antonkulaga** [polynote/polynote#755]
When I click on a cell select box I see Scala/Python/SQL/Vega_Spec, but no markdown options. When I use the top dropbox I see one more option Scala/Python/SQL/Vega_Spec/Text , that is better (although weird as I would expect to have same number of options inside the cell) but the text option does not seem to support markdown. 
Please, add markdown!

**Comment by jonathanindig** [comment]
The text dropdown not being available in the cell drop down was intentional, please see #632 for more information. As indicated, we're willing to revisit that decision given more data points. Please feel free to continue the discussion on that issue. 

You're right that the text option doesn't support Markdown. While imperfect (see #12), it is a rich text editor. 

Can you elaborate as to why you would like Markdown support? Are there any features you're missing in the current text editor?

**Comment by antonkulaga** [comment]
>Can you elaborate as to why you would like Markdown support? Are there any features you're missing in the current text editor?

It is just a habit as in most of other notebooks all text cells are markdown by default

**Comment by jeremyrsmith** [comment]
FWIW, I agree that we should have an option for Markdown. The rich text is fancy, but a lot of people would prefer to just write markdown. I just haven't had time to add this yet. I don't think it would be all that difficult, it just hasn't been a priority for us so far (our internal users are divided between "prefer the rich text editor" and "I don't really use text cells so it doesn't matter")

**Comment by daveray** [comment]
+1 for markdown. The rich editor is just kind of flaky. It gets into weird states (especially if I try to change the text style, say to "Heading 2") so I end up having to just delete the cell and start over to get the formatting I want.

One thing that would make the rich text editor less tedious would be to move the text controls into the cell itself when editing so I don't have to keep going all the way back to the top of the page.

**Comment by omidmogasemi** [comment]
This is currently being worked on. The current approach is as follows: 
- A user will have the option to toggle between the current rich text editor and a traditional Markdown editor 
- This Markdown editor will support traditional Markdown syntax, with the behavior as follows: 
   * When a user has Markdown editing enabled and clicks away, their code will compile as in a traditional Markdown editor 
   * Clicking back on the cell will convert the compiled Markdown back to a traditional editor, where all of their syntax is visible
