### ISSUE TITLE
show all running kernels/notebooks in one place

### ISSUE THREAD

**Issue by antonkulaga** [polynote/polynote#771]
Quite often I forget to switch off the kernel at some notebooks that leads to inefficient usage of the resources, I think there should be a way to see status of all notebooks. The easiest way can be changing the color of icons of the notebooks in the left sidebar to green (if started) and yello (if active) and also give a filter to show all notebooks, or all active notebooks.

**Comment by jonathanindig** [comment]
Hi @antonkulaga, we do have a way for you to see the currently running kernels. Click the ⚙️icon at the top right and then click on "Running Kernels" and you should see a list of all active kernels. 

We also have https://github.com/polynote/polynote/issues/379 which I believe addresses your suggestion of putting some information about running kernels in the sidebar. I'll close this issue in favor of that one, thanks!
