### ISSUE TITLE
Integration with Apache Livy

### ISSUE THREAD

**Issue by ChethanUK** [polynote/polynote#772]
How to integrate with Apache Livy?

In Jupyter there is Sparkmagic.
![image](https://user-images.githubusercontent.com/16241795/73597855-b25a7c80-4556-11ea-9cb6-fbda8755b996.png)

**Comment by jonathanindig** [comment]
From my understanding of how Livy works, I don't think integration with it makes a lot of sense for Polynote. I don't think we'd be able to provide many of our core features like code completion and interop between languages.
