### ISSUE TITLE
usage kernel.display.html inside functions is broken when called from another cells

### ISSUE THREAD

**Issue by antonkulaga** [polynote/polynote#793]
kernel.display.html is a way to get reasonable visualization with html+javascript. So, I write functions that calls kernel.display.html inside of themselves to draw charts. However, kernel.display.html does not work when it is called inside functions (only exception if the cell is the same when the function is declared). Here is a screenshot that illustrates the problem

![Screenshot_2020-02-20 figures ipynb Polynote](https://user-images.githubusercontent.com/842436/74888100-b6273500-5385-11ea-915b-c3fe9d03d4a0.png)

**Comment by jonathanindig** [comment]
Closing since #796 provided a workaround (add the implicit parameter `(implicit kernel: polynote.runtime.KernelRuntime)` to your function and use that `kernel`), even though this is not ideal.
