### ISSUE TITLE
Add visualization widgets (e.g. with plotly.js)

### ISSUE THREAD

**Issue by raproth** [polynote/polynote#797]
I'm using spark-notebook (https://github.com/spark-notebook/spark-notebook) with spark/scala for 4 years now but looking for alternatives now. polynote looks great and could possibly outperform spark-notebook.

But it would be great to support _plot.ly_ javascript interface as it was possible in spark-notebook. They made a wrapper-class `CustomPlotlyChart` to generate and render plots of dataframes. 

Alternatively, I'm interested to see some examples how to implement reusable (scala) functions which renders dataframes into vega charts, is it currently possible?

**Comment by raproth** [comment]
I just played around a bit, it seems possible to include plot.ly charts using kernel.display.html(....):

![image](https://user-images.githubusercontent.com/20788208/75092307-90ad4d80-5576-11ea-8d60-0e1e9806ffc2.png)

So a function which takes a dataframe and renders a plot.ly chart should be possible

**Comment by raproth** [comment]
The label on this issue is confusing, this has nothing to do with python, I'm only using scala...

**Comment by jonathanindig** [comment]
Oh sorry, I thought plotly was a Python thing. 

I guess I'm not sure what behavior you are expecting from Polynote - can you share an example of what you are expecting Polynote to do with plotly? I'm not familiar with spark-notebook.

**Comment by raproth** [comment]
Plotly is a javascript-library (a Python API is available). Plotly was just one example, this could also be done using other frameworks. What I basically miss is the possibility to define functions which produce a plot when called, this could look like this:

![image](https://user-images.githubusercontent.com/20788208/75282907-1c8ed600-5812-11ea-971e-3cb4cd5a998f.png)

The plot should be rendered **without any user interaction** like clicking together dimensions etc.

**Comment by jonathanindig** [comment]
Would #796 help to address the problem? 

```scala
import polynote.runtime.KernelRuntime
def plot(df: DataFrame, xCol: String, yCol: String, plotStyle: String)(implicit kernel: KernelRuntime) = {
  val plotStr = ??? // set up plotly.js plot
  kernel.display.html(plotStr)
}
```

**Comment by raproth** [comment]
Yes, this works, thanks!

I would still be interested so see if such functionality is possible with vega (encapsulate vega-spec in method?). If not, it would be great to have some built in widgets to make reusable plotting functions

**Comment by jonathanindig** [comment]
Cleaning up old issues, seems like this one is resolved.

**Comment by antonkulaga** [comment]
As there is plotly scala binding maybe you can consider adding scala-based plotly? https://github.com/polynote/polynote/issues/1191
