### ISSUE TITLE
implicit kernel does not always work

### ISSUE THREAD

**Issue by antonkulaga** [polynote/polynote#814]
I noticed that when I use  kernel.display.html implicit kernel works
```
def div(id: String)(implicit kernel: KernelRuntime) = kernel.display.html(s"""<div id="${id}"></div>""")
```
however if in one of the previos cells I had
```
import kernel.display.html
```
and then in one of the following cells I have
```
def div(id: String)(implicit kernel: KernelRuntime) = html(s"""<div id="${id}"></div>""")
```
implicit kernel does not take into account. In other words "kernel.display.html(" takes implicit kernel while "html(" does not take it, but executes the nonhtml part of the code.

**Comment by JD557** [comment]
This seems like a problem with your code. When you perform that import, you are reffering to the kernel explicitly.

I think what you want to do is:

```scala
def html(implicit kernel: KernelRuntime) = kernel.display.html
//-------------
def div(id: String)(implicit kernel: KernelRuntime) = html(s"""<div id="${id}"></div>""")
```

I guess that, alternatively, the `kernel` could be renamed to something like `unsafeKernel` and the `kernel` operation could simply be an alias to the operation on the current runtime`kernel.display.html(implicit kernelRuntime: KernelRuntime)`. At least this would make it obvious that you are not supposed to use `unsafeKernel`...

**Comment by jonathanindig** [comment]
Cleaning up old issues. Thanks @JD557 for stepping in with a great explanation 😄
