### ISSUE TITLE
stop button does not seem to work

### ISSUE THREAD

**Issue by antonkulaga** [polynote/polynote#816]
Whever I have any dataframe and I run something like:
```
df.show(100,1000)
```
it runs until it will display all the results even if I push "stop cell" multiple time during execution

**Comment by jeremyrsmith** [comment]
Is this a Spark data frame or pandas?

**Comment by antonkulaga** [comment]
It is spark-one in Scala cell

**Comment by jeremyrsmith** [comment]
This should be fixed by #856 – please reopen if you still see this behavior in 0.3.6.
