### ISSUE TITLE
The connection was reset

### ISSUE THREAD

**Issue by igormcsouza** [polynote/polynote#833]
Hey! Everyone.. I had a little problem here trying to run this container.. let's get to it...

**Description**
I had downloaded the image from this repo and run as asked. But when I started the browser I got the error *The connection was reset*. The polynote logo is on the terminal, everything looks ok, but the connection is not!

**Reproduction**
1. Download the image
2. Run it
3. Open the browser and type 127.0.0.1:8192

**Environment**
docker run --rm -it -p 127.0.0.1:8192:8192 -p 127.0.0.1:4040-4050:4040-4050 -v `pwd`/config.yml:/opt/config/config.yml -v `pwd`/notebooks:/opt/notebooks/ polynote/polynote:latest --config /opt/config/config.yml

Otherwise, please provide the following information:
- Polynote Version: 
   - Example: 0.3.3
- Operating System: 
Linux Ubuntu 19.10
- How you installed Polynote: 
From Container

**Comment by igormcsouza** [comment]
Found the fix! Change network to host made it work

**Comment by jonathanindig** [comment]
Hi @igormcsouza did you try following these instructions when you were trying to get Polynote to work in Docker? https://github.com/polynote/polynote/tree/master/docker#usage-instructions
