### ISSUE TITLE
Polynote does not open notebook with Javascript error

### ISSUE THREAD

**Issue by siddhartha-gadgil** [polynote/polynote#868]
**Description**
A new notebook called "test.ipynb" does not open. The javascript console gives the following error.
```
nb_config.ts:167 Uncaught TypeError: Object.fromEntries is not a function
    at new dde (nb_config.ts:167)
    at cde.setConfig (nb_config.ts:34)
    at new cde (nb_config.ts:29)
    at new hde (nb_cells.ts:27)
    at new yde (notebook.ts:109)
    at Function.getOrCreate (notebook.ts:64)
    at Tde.loadNotebook (ui.ts:274)
    at Tde.subscribe.e (ui.ts:250)
    at Tde.publish (ui_event.ts:68)
    at Dde.publish (ui_event.ts:76)
```

**Reproduction**
1. Install polynote
2. Create notebook
3. Click to open

**Environment**
Are you using the official Docker distribution? If so, please provide your `docker run` command and any other details that may be relevant (mount points, etc). 

Otherwise, please provide the following information:
- Polynote Version: 0.3.6
- Operating System: Ubuntu 18.04
- JVM Version: 1.8.0_181
- Python Version: 3.7.6 (not used)
- How you installed Polynote: I downloaded this release https://github.com/polynote/polynote/releases/download/0.3.6/polynote-dist.tar.gz and then followed [these instructions](https://polynote.org/docs/01-installation.html).
- The command you are using to start Polynote: ./polynote.jar
- Any other details that might be useful, such as whether you are running Polynote as a service, using a custom script, etc.  

**Configuration**
If applicable, please attach or paste your Polynote configuration (`config.yml`)

**Notebook**
If applicable, please attach or paste the notebook file (`.ipynb`) you were trying to run when you see this bug. 

**Logs**
If applicable, please attach or paste the Polynote log

**Screenshots**
If applicable, please attach screenshots to help explain your problem.

**Additional context**

**Comment by raproth** [comment]
you should run `polynote.py`, not `polynote.jar`, maybe that solved the issue?

**Comment by siddhartha-gadgil** [comment]
Unfortunately I get the same error.

**Comment by jeremyrsmith** [comment]
@siddhartha-gadgil which browser are you using?

**Comment by siddhartha-gadgil** [comment]
Chrome on Ubuntu

**Comment by siddhartha-gadgil** [comment]
I should be more specific : chrome on Ubuntu "Version 71.0.3578.98 (Official Build) (64-bit)". 

I see from the [mdn](https://developer.mozilla.org/enUS/docs/Web/JavaScript/Reference/Global_Objects/Object/fromEntries) page that this is supported only from version 73. But I am allowing autoupdates.

**Comment by siddhartha-gadgil** [comment]
When I use firefox I have no problem

**Comment by jeremyrsmith** [comment]
Hmm, that browser version is roughly a year old at this point. We'll add a polyfill for `Object.fromEntries` (or rework that code to avoid it) but I'm not sure what other issues will come up.

**Comment by siddhartha-gadgil** [comment]
Looks like I made a mistake, assuming chrome is auto updating on Ubuntu. I just downloaded a recent version and polynote works fine for me.

**Comment by jeremyrsmith** [comment]
:+1: good to hear!
