### ISSUE TITLE
Plot editor is unable to plot `Array` with no error message

### ISSUE THREAD

**Issue by jonathanindig** [polynote/polynote#873]
Run the following cell:
```
(1 to 10).map { i => (i, i*i)} toArray
```
Try to use the plot editor to plot a simple bar chart - it doesn't work. There are no errors in the console. 

Now, try 
```
(1 to 10).map { i => (i, i*i)} toList
```

And the plot editor works!

**Comment by jeremyrsmith** [comment]
Fixed by #875
