### ISSUE TITLE
Unable to run Python code

### ISSUE THREAD

**Issue by rsotogar** [polynote/polynote#902]
Hi guys,

I am new to polynote so this might be a begginers mistake. I get this error when executing Python cells on my notebook. The packages are supposed to be installed in the "configuration and dependencies" section, but I get this error when running the cells.

![Screenshot 2020-05-13 at 17 32 15](https://user-images.githubusercontent.com/59261157/81839656-c0e60600-953f-11ea-9077-dbaf75fbdadf.png)

I am used to installing python packages via Anaconda, so this might involve a little bit of more work.

Thanks!

**Comment by jonathanindig** [comment]
How did you install Polynote? Did run  `pip3 install -r ./requirements.txt`? (see the bottom of https://github.com/polynote/polynote/blob/master/docs/01-installation.md#prerequisites)

**Comment by rsotogar** [comment]
I run all the above steps but I get an error when running pip3 install -r ./requirements.txt. I have Python 3 and pip installed, but not pip3. Is this a must? If so, how can I install pip3 on MacOS?

**Comment by rsotogar** [comment]
Please see below. Now I have pip3, but it cannot locate the requirements.txt file

![Screenshot 2020-05-13 at 19 30 48](https://user-images.githubusercontent.com/59261157/81850780-5d180900-9550-11ea-9300-507ae55797eb.png)

**Comment by jonathanindig** [comment]
pip3 is just the python 3 version of pip. Your system's `pip` might already be using Python 3. 

You need to execute that command in the Polynote release folder. 

Feel free to jump over to gitter if you need more help! https://gitter.im/polynote/polynote
That's a better forum for these sorts of questions and there are more people hanging out there that can give you a hand 😄
