### ISSUE TITLE
Kernel Does not Turn On

### ISSUE THREAD

**Issue by TancrediCP** [polynote/polynote#919]
**Description**

After I run ./polynote.py Polynote start-ups however when I then attempt to use it the Kernel won't turn on (The 'light' near the kernel just remains grey regardless of what I attempt to do). First attempt at running polynote. I am using a virtual environment. 

**Reproduction**
./polynote.py

**Environment**
- Polynote Version: 0.3.8
- Operating System: Mac OS Mojave 10.14.6
- JVM Version: 
java version "14.0.1" 2020-04-14
Java(TM) SE Runtime Environment (build 14.0.1+7)
Java HotSpot(TM) 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)
- Python Version: Python 3.7.7 

- How you installed Polynote: 
Followed these instructions https://polynote.org/docs/01-installation.html
 

**Configuration**
Default Configuration

**Notebook**
NA

**Logs**
None

**Screenshots**
NA

**Additional context**
NA

**Comment by jonathanindig** [comment]
Try creating the folder `/Users/user/Desktop/polynote/notebooks`

**Comment by TancrediCP** [comment]
Error Logs Have disappeared but issue is the same - Kernel is absent.

**Comment by TancrediCP** [comment]
It worked! Notebooks only seem to work if they are inside the spefic /Users/user/Desktop/polynote/notebooks directory
