### ISSUE TITLE
First cell cannot be changed to python

### ISSUE THREAD

**Issue by raproth** [polynote/polynote#933]
With the current master of polynote (440f95fd102e6f0a68a54c72d81ac9cc27adec17), it seems that the first cell cannot be changed to python in a newly created notebook. Even if I chose "Python", the symbol does not change and I cannot execute valid python code.

![image](https://user-images.githubusercontent.com/20788208/86327435-a0831f80-bc43-11ea-8cfd-5b562ec7a316.png)

How to reproduce:
create new notebook --> add code cell --> change type to python

**Comment by amalshaji** [comment]
It seems working now.

**Comment by jonathanindig** [comment]
@raproth I'm unable to reproduce. Do you still see this issue on current master? How are you running Polynote?
