### ISSUE TITLE
should respect def _repr_html_(self):

### ISSUE THREAD

**Issue by antonkulaga** [polynote/polynote#935]
Unlike jupyter it does not show def _repr_html_(self): in the output :-(

**Comment by jonathanindig** [comment]
Hi @antonkulaga, can you please provide more information about what's not working? It seems to work fine for me: 

![Screen Shot 2020-07-20 at 12 40 16 PM](https://user-images.githubusercontent.com/5430417/87978981-34e3e380-ca86-11ea-84c5-f963740a5b96.png)

**Comment by antonkulaga** [comment]
repr_html(self) of pandas dataframe is not taken into account. And I am talking about regular pandas, not spark-pandas.

**Comment by jonathanindig** [comment]
Currently Polynote displays the schema and inspector shortcuts, just like it does for Spark dataframes. 

<img width="1426" alt="Screen Shot 2020-08-03 at 4 14 22 PM" src="https://user-images.githubusercontent.com/5430417/89236129-9dfa4980-d5a4-11ea-974a-c77ce228b463.png">

The HTML view is available in the inspector, if you click on the HTML section. 

<img width="1619" alt="Screen Shot 2020-08-03 at 4 14 31 PM" src="https://user-images.githubusercontent.com/5430417/89236313-0d703900-d5a5-11ea-9d4d-4612ce2b1dc5.png">

If you want to display the HTML output of the dataframe, you can call it directly: 

<img width="980" alt="Screen Shot 2020-08-03 at 4 19 49 PM" src="https://user-images.githubusercontent.com/5430417/89236354-30025200-d5a5-11ea-8c36-43eb756beec0.png">

**Comment by jonathanindig** [comment]
We are working on some changes to the way we display data based on your (and other's) feedback about the modal display. Stay tuned! 

I'll close this issue for now as it doesn't seem to be about `_repr_html_` as such, but please feel free to continue to discuss here and provide feedback. Thanks!
