### ISSUE TITLE
script/polynote failure ls: cannot access 'deps/*.jar': No such file or directory

### ISSUE THREAD

**Issue by RakanBinAbdullah** [polynote/polynote#937]
`./polynote
+ cd .
++ pip3 show jep
++ grep '^Location:'
++ cut -d : -f 2
++ cut -d ' ' -f 2
+ jep_path=/home/Rakan/.local/lib/python3.8/site-packages
++ dirname /home/Rakan/.local/lib/python3.8/site-packages
+ python_lib_path=/home/Rakan/.local/lib/python3.8
++ dirname /home/Rakan/.local/lib/python3.8
+ python_path=/home/Rakan/.local/lib
+ test -e /home/Rakan/.local/lib/libpython3.so
+ export LD_PRELOAD=/home/Rakan/.local/lib/libpython3.so
+ LD_PRELOAD=/home/Rakan/.local/lib/libpython3.so
+ test -e plugins.d
+ deps=($(ls deps/*.jar))
++ ls 'deps/*.jar'
ls: cannot access 'deps/*.jar': No such file or directory`

**Comment by jonathanindig** [comment]
@RakanBinAbdullah what release are you using? The `./polynote` script hasn't been packaged for a long time. Please download the latest release and use the `./polynote.py` script instead. 

Also as I see you're using Python 3.8, please note that we don't test Polynote with Python 3.8 since it's not supported by Spark 2.x.

**Comment by RakanBinAbdullah** [comment]
@jonathanindig I'm using 0.3.11, even when trying `./polynote.py`
output:
```
File "./polynote.py", line 30, in <module>
    raise Exception("Couldn't find the deps directory. Are we in the polynote installation directory?")
Exception: Couldn't find the deps directory. Are we in the polynote installation directory?
```
where I could find these jar files, is it some java compressed file or something ??

**Comment by conderls** [comment]
> @jonathanindig I'm using 0.3.11, even when trying `./polynote.py`
> output:
> 
> ```
> File "./polynote.py", line 30, in <module>
>     raise Exception("Couldn't find the deps directory. Are we in the polynote installation directory?")
> Exception: Couldn't find the deps directory. Are we in the polynote installation directory?
> ```
> 
> where I could find these jar files, is it some java compressed file or something ??

I think you using the source code, compilation required (sbt assembly). you can download [polynote-dist](https://github.com/polynote/polynote/releases),  files in which are:
```
# polynote-dist.tar.gz, polynote-dist-2.12.tar.gz
polynote
├── config-template.yml
├── deps  ## <---------    there is `deps`
├── examples
├── plugin
├── polynote.jar
├── polynote.py
├── requirements.txt
└── static
```

**Comment by RakanBinAbdullah** [comment]
@jonathanindig appreciate it
