### ISSUE TITLE
NameErrors in Python Data Classes

### ISSUE THREAD

**Issue by jonathanindig** [polynote/polynote#942]
We're getting a `NameError` when dataclasses reference class types. 

![Screen Shot 2020-07-29 at 11 45 59 AM](https://user-images.githubusercontent.com/5430417/88840404-3ea9cd00-d191-11ea-9a13-17ec67f0a6d4.png)

**Comment by antonkulaga** [comment]
Most of my classes are dataclass 'cause it is super-convenient and they resamble case classes in Scala. So, I will be very happy if dataclasses will work smoothly.
