### ISSUE TITLE
Notebook Runner Just Hangs

### ISSUE THREAD

**Issue by larsskaug** [polynote/polynote#953]
The notebook runner does not seem to work, and provides no output as to why. It just hangs.

Ran the following command
polynote.py run helloWorld.ipynb

The notebook only contains one one cell, with one statement.:
println("Hello")

**Comment by jonathanindig** [comment]
Hi @larsskaug I see you asked us about this issue on Gitter. The Notebook Runner seems to be working fine for me. If you  provide more information about your environment, we might be able to help you. 

When you create a new issue, there's a helpful [`Bug Report` template](https://github.com/polynote/polynote/issues/new?assignees=&labels=&template=bug_report.md&title=), did you see that button? This template has information that would help us diagnose your issue, so please do fill it out if you'd like us to be able to assist you.
