### ISSUE TITLE
Insert/edit equation button can be clicked all the time.

### ISSUE THREAD

**Issue by echohlne** [polynote/polynote#969]
The `Insert/edit equation` button can be clicked all the time, causing the page to display several input dialogs.
I'm not sure if this is normal or not? Maybe the button should be disabled after the pop-up dailog.

![equation](https://user-images.githubusercontent.com/52202080/93621289-eadb9780-fa0d-11ea-95c2-865ec45a0aa7.png)

**Comment by jeremyrsmith** [comment]
It certainly doesn't look normal to me... does this happen in Chrome or a different browser?

**Comment by jeremyrsmith** [comment]
This bug looks pretty hilarious though either way 😆  thanks for reporting it!

**Comment by akiyamaneko** [comment]
Both Chrome and Firefox have the problem. I submitted a PR(#970 ) to try to fix this problem, please help to review it.
