### ISSUE TITLE
Skipped stages remain as queued tasks 

### ISSUE THREAD

**Issue by indig** [polynote/polynote#98]
Skipped stages remain in the task queue indefinitely, looks like we aren't marking them as complete when they get skipped.

**Comment by jeremyrsmith** [comment]
Hmm, can't quite figure out why this happens. As long as the job completes (and the listener is notified of such) they should get cleaned up: https://github.com/polynote/polynote/blob/master/polynote-spark/src/main/scala/polynote/kernel/KernelListener.scala#L47

**Comment by jeremyrsmith** [comment]
Solved (kinda) by #131 (we don't show all the queued stages anymore)
