### ISSUE TITLE
Issue with spark support in 3.12 docker image

### ISSUE THREAD

**Issue by andrewresearch** [polynote/polynote#982]
**Description**
The docker image for 0.3.12-2.11-spark2.4 works for non-spark notebooks, but fails with spark notebooks with the following error:

```[ERROR]   (Logged from NotebookSession.scala:174)
   |     java.io.IOException: Cannot run program "spark-submit": error=2, No such file or directory
   |     java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
   |     polynote.kernel.remote.SocketTransport$DeploySubprocess$$anonfun$deployKernel$1$$anonfun$apply$65$$anonfun$apply$66$$anonfun$apply$67$$anonfun$apply$68$$anonfun$apply$69.apply(transport.scala:347)
   |     polynote.kernel.remote.SocketTransport$DeploySubprocess$$anonfun$deployKernel$1$$anonfun$apply$65$$anonfun$apply$66$$anonfun$apply$67$$anonfun$apply$68$$anonfun$apply$69.apply(transport.scala:347)
   |     zio.internal.FiberContext.evaluateNow(FiberContext.scala:458)
   |     zio.internal.FiberContext.zio$internal$FiberContext$$run$body$2(FiberContext.scala:687)
   |     zio.internal.FiberContext$$anonfun$12.run(FiberContext.scala:687)
   |     java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   |     java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   |     java.lang.Thread.run(Thread.java:748)
```

**Reproduction**
1. Run docker image 0.3.12-2.11-spark2.4 without spark - works fine
2. Test with spark_master set to local[*] in spark config - fails with Kernel error as above
3. Try same process with previous version docker image (0.3.12-2.11-spark2.4) - works fine

**Environment**
Are you using the official Docker distribution? If so, please provide your `docker run` command and any other details that may be relevant (mount points, etc). 

```
export POLYNOTE_VERSION="0.3.11-2.11-spark2.4"
docker run --name polynote -it -p 127.0.0.1:8192:8192 -p 127.0.0.1:4040-4050:4040-4050 -v `pwd`/polynote/config.yml:/opt/config/config.yml -v /Users/username/projects/_notebook_repos:/opt/notebooks/ -v /Users/username/.ivy2/local:/home/polly/.ivy2/local polynote/polynote:$POLYNOTE_VERSION --config /opt/config/config.yml
```

Otherwise, please provide the following information:
- Polynote Version: 
   - Example: 0.2.12
- Operating System: 
  - Example: Mac OS Mojave 10.14.6
- JVM Version:
  - Example: 1.8.0_212
- Python Version:
  - Example: 2.7.15
- How you installed Polynote: 
  - Example: I downloaded this release https://github.com/polynote/polynote/releases/download/0.2.12/polynote-dist.tar.gz and then followed [these instructions](https://polynote.org/docs/01-installation.html).
- The command you are using to start Polynote:
  - Example: `./polynote.py`
- Any other details that might be useful, such as whether you are running Polynote as a service, using a custom script, etc.  

**Configuration**
If applicable, please attach or paste your Polynote configuration (`config.yml`)

**Notebook**
If applicable, please attach or paste the notebook file (`.ipynb`) you were trying to run when you see this bug. 

**Logs**
If applicable, please attach or paste the Polynote log

**Screenshots**
If applicable, please attach screenshots to help explain your problem.

**Additional context**

**Comment by jonathanindig** [comment]
Hi @andrewresearch, thanks for the report! 

It looks like we weren't using the right link in our CI build to download spark: it seems like the https://downloads.apache.org/spark/spark-2.4.5/spark-2.4.5-bin-hadoop2.7.tgz disappears when they release a new version, and we should be using https://archive.apache.org/dist/spark/spark-2.4.5/spark-2.4.5-bin-hadoop2.7.tgz instead. I'll fix our docker build script to point to the latest version.

**Comment by greenmaid** [comment]
Hello,

The docker image `0.3.12-2.11-spark2.4` still doesn't contains spark

I got:
```
$ docker run --rm --entrypoint="" polynote/polynote:0.3.12-2.11-spark2.4 ls 
polynote
```
where previous version gives:
```
> docker run --rm --entrypoint="" polynote/polynote:0.3.11-2.11-spark2.4 ls 
install_spark.sh
polynote
spark
spark-2.4.5-bin-hadoop2.7.tgz
```

**Comment by aviatesk** [comment]
Same issue here, and I also would like to point out that spark 2.12 is incompatible with spark 2.4, which means `polynote/polynote:0.3.12-2.12-spark2.4` can't be used with spark (the same actually applied to `polynote/polynote:0.3.11-2.11-spark2.4`
