### ISSUE TITLE
Getting Error starting cell in python

### ISSUE THREAD

**Issue by shawel** [polynote/polynote#984]
I am not sure what the problem is: Scala works fine and the PATH variables checkout
```
/usr/local/lib/python3.7/site-packages/jep/libjep.jnilib: dlopen(/usr/local/lib/python3.7/site-packages/jep/libjep.jnilib, 1): Library not loaded: /usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/Python
  Referenced from: /usr/local/lib/python3.7/site-packages/jep/libjep.jnilib
  Reason: image not found
```

<img width="1368" alt="Screen Shot 2020-10-08 at 12 09 49 PM" src="https://user-images.githubusercontent.com/625370/95485703-1a702680-0960-11eb-80ca-df453c8548d7.png">

**Comment by jonathanindig** [comment]
Hello @shawel. Please provide more information about your environment. How are you running Polynote? How is Python installed? We have a [Bug Report issue template](https://github.com/polynote/polynote/issues/new?assignees=&labels=&template=bug_report.md&title=) which prompts for the information we need to help debug these issues. 

Have you looked at [these other issues ](https://github.com/polynote/polynote/issues?q=unsatisfiedlinkerror)where people have reported the same problem?

**Comment by jonathanindig** [comment]
Hi @shawel, I hope you were able to resolve this problem. I'm going to close this issue for now, but if you still need help please feel free to comment with the information I requested above. Thanks!
