### ISSUE TITLE
Import modules

### ISSUE THREAD

**Issue by pixie79** [polynote/polynote#991]
**Description**
I have built a local copy of the docker container using scala 2.12, with Hadoop 3.0.1. I am trying to test some local modules and IOT with Azure.

However It seems i can not import modules:

**Reproduction**
1. I have added a local repo to the config and added the modules as dependencies to the notebook. (This appears to have pulled in the POM's ok at least)
2. If i then try to import the modules I get an error

```scala
import org.apache.spark.sql.SparkSession
import org.apache.spark.sql.streaming.Trigger
import org.apache.spark.eventhubs._
import org.apache.spark.sql._
import org.apache.spark.sql.functions._
import org.apache.spark.sql.types._
import io.delta
```
Error:

Error object SparkSession is not a member of package org.apache.spark.sql (Line 1)
Error object streaming is not a member of package org.apache.spark.sql (Line 2)
Error object functions is not a member of package org.apache.spark.sql (Line 5)
Error object types is not a member of package org.apache.spark.sql (Line 6)

**Environment**
Are you using the official Docker distribution? If so, please provide your `docker run` command and any other details that may be relevant (mount points, etc). 

Otherwise, please provide the following information:
- Polynote Version: 
   - 0.2.12

- JVM Version:
  - openjdk:8-slim-buster

Built the standard docker but with the following overrides
export SPARK_VERSION=3.0.1
export SCALA_VERSION=2.12
export HADOOP_VERSION=3.2.1
export HADOOP_MAJOR_VERSION=3.2

**Comment by jeremyrsmith** [comment]
Does your notebook have any Spark configuration set? Currently, Polynote won't initialize a Spark-based kernel unless there exists at least one Spark configuration (e.g. `spark.driver.memory` or some other configuration). If there are no Spark configurations, it uses a non-Spark kernel and it won't inherit the Spark classpath.

**Comment by pixie79** [comment]
Ah ok


No I didn't realise that. What would be the correct way to set that in the
notebook?

Thanks

**Comment by jeremyrsmith** [comment]
@pixie79 if you open the "Configuration and Dependencies" panel at the top of the notebook, it has a section for Spark configuration. Add one or more key/value config item(s) to this and then click "Save".

Closing this issue, assuming that's the problem. If you still get this error, feel free to reopen.
